import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { ArkFile } from 'arkanalyzer/lib/core/model/ArkFile';
import { Rule, Defects, MatcherCallback } from '../../Index';
import { IssueReport } from '../../model/Defects';
export declare class ConstantPropertyReferencingInLoopsCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    private valueStr;
    private indexStr;
    private isArrayStaticField;
    private isIndexConstant;
    private isStaticFieldConstant;
    private isRecursiveStart;
    private recursiveTime;
    defects: Defects[];
    issues: IssueReport[];
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    private constantCheckByArkMethods;
    private constantCheckByArkStmts;
    private setVariableMapByValue;
    private constantCheckByCycliStmts;
    private constantCheckByAssignStmt;
    private checkByStaticFieldRef;
    private checkByBinopExpr;
    private checkByArrayRef;
    private handleRecursiveIndex;
    private handleNonRecursiveIndex;
    private updateIndexStr;
    private checkByIfStmt;
    private checkReportAndInit;
    private initData;
    private dealWithElse;
    private withoutVariableMapOperation;
    private getValueStr;
    private getVariableMap;
    private getVariableMapByLocal;
    private getCyclicStmts;
    private getExternalVariables;
    private isExist;
    private getDeclaringName;
    private isExistIssueReport;
    private pushIssueReports;
    private getWarnInfo;
}
