import { Scene } from 'arkanalyzer';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, MatcherCallback, Rule } from '../../Index';
import { IssueReport } from '../../model/Defects';
export declare class AvsessionMetadataCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    registerMatchers(): MatcherCallback[];
    check: (scene: Scene) => void;
    private processClass;
    private processReportIssue;
    private getMultipleScenariosField;
    private getNewName;
    private getField;
    private traversalLocals;
    private traversalFields;
    private traversalStaticFields;
    private traversalDefaultClass;
    private isArkFieldGetFields;
    private isHasAuthorAndSubtitle;
    private processArkMethod;
    private isAwaitReturnStmt;
    private getPromiseThenCallbackMethod;
    private processCallbackMethod;
    private handleInvokeStmt;
    private handleInvoker;
    private parseRealAttachInstance;
    private isArgTypeMultimedia;
    private getInvokeCallbackMethod;
    private parseInvokerAudioInterruptStmt;
    private setStmt;
    private getFieldByBase;
    private commonInvokerMatch;
    private findMatchingStmt;
    private isInvokerAndStmtMatch;
    private isDesignatedField;
    private getReturnOp;
    private isResolveAssignToVariable;
    private isInstanceAssignToVariable;
    private isType;
    private isMultimediaCreateStmt;
    private isAudioInterruptStmt;
    private reportIssue;
}
