/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let { itemId, list } = {},
  obj = [],
  total = 0;
total = 9;
console.log(itemId, list, obj, total);

let { itemId1, list1 } = {},
  obj1 = [];
console.log(itemId1, list1, obj1);

let [ itemId2, list2 ] = [],
  total2 = 0;
total2 = 9;
console.log(itemId2, list2, total2);

let [ itemId3, list3 ] = [],
  obj3 = [];
console.log(itemId3, list3, obj3);