import { ArkFile } from "arkanalyzer";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { MatcherCallback } from '../../Index';
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
export declare class AwaitThenableCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private symbolTable;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    private checkClass;
    private checkMethod;
    private checkStmt;
    private checkAwaitThenable;
    private isAwaitExpression;
    private isPossiblePromiseOrThenable;
    private checkParameterTypeNode;
    private checkOptionalChain;
    private checkIdentifier;
    private checkCallExpression;
    private checkCallExpressionIdentifier;
    private analyzeFunctionBodyForPromise;
    private isPromiseVariableDeclaration;
    private isPromiseIntersectionTypeNode;
    private isPromiseTypeReferenceNode;
    private isPromiseConstructorCall;
    private isPromiseCallExpression;
    private isPromiseOrSubclass;
    private isPromiseExpressionWithTypeArguments;
    private isAsyncFunctionCall;
    private buildSymbolTable;
    private buildSymbolTableAddParam;
    private hasThenMethod;
    private addIssueReportNode;
}
