import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { MatcherCallback } from "../../Index";
export declare class CommaSpacingCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private arkFile;
    private options;
    private inMultiLineComment;
    check(target: any): void;
    registerMatchers(): MatcherCallback[];
    private checkLine;
    private shouldSkipLine;
    private processCommas;
    private shouldSkipComma;
    private checkCommaSpacing;
    private getSpacingContext;
    private shouldSkipSpacingCheck;
    private isArrayFirstCommaWithElement;
    private checkBeforeSpacing;
    private checkAfterSpacing;
    private isConsecutiveComma;
    private hasRealElementBeforeComma;
    private isBracketContext;
    private hasContentBetweenBracketAndComma;
    private isEmptyArrayElement;
    private isTrailingComma;
    private calculateAbsolutePosition;
    private addDefect;
    private getFix;
    private cacheRanges;
    private findCommentRanges;
    private findStringRanges;
    private handleEscapeCharInString;
    private handleStringStart;
    private handleStringEnd;
    private findRegExpRanges;
    private validateRegExpRange;
    private isInRanges;
    private isInString;
    private updateStringState;
    private handleEscapeChar;
    private handleTemplateExpression;
    private updateBraceCount;
    private updateQuoteState;
    private isInRegExp;
    private isGenericTrailingComma;
    private isCommaAfterComment;
    private hasArrayOrObjectLiteral;
    private isValidLastCharBeforeComment;
    private findLastNonWhitespaceChar;
    private isCommaBeforeComment;
    private isEndOfLine;
}
