import { ArkFile } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { MatcherCallback } from "../../Index";
export declare class CommaDangleCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    issues: IssueReport[];
    defects: Defects[];
    rule: Rule;
    private Special;
    private Trailing1;
    private Trailing2;
    private CommasAndSpaces;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    private getRuleOption;
    check: (target: ArkFile) => void;
    private checkFunction;
    private findTrailingCommaPos;
    private checkTrailingComma;
    private shouldSkipArrayCheck;
    private getTrailingCommaInfo;
    private processTrailingCommaViolation;
    private reportTrailingCommaViolation;
    private isSpecialSpacedCommaCase;
    private isArrayWithOnlyCommasAndSpaces;
    private checkEnumTrailingComma;
    private checkInvalidEnumValues;
    private reportInvalidEnumValue;
    private extractGenericInfo;
    private checkGenericViolationRules;
    private reportGenericViolation;
    private createGenericFix;
    private checkFunctionGenericComma;
    private checkArrowGenericComma;
    private checkTupleTrailingComma;
    private shouldCheckTuple;
    private getTupleContext;
    private checkTupleViolation;
    private reportTupleViolation;
    private createTupleDefect;
    private createTupleFix;
    private hasTrailingComma;
    private isMultiline;
    private checkImportExportTrailingComma;
    private hasFunctionTrailingComma;
    private checkFunctionTrailingComma;
    private checkCallExpressionComma;
    private isReduceMethodCall;
    private checkReduceMethodComma;
    private checkNewExpressionComma;
    private checkFunctionDeclarationComma;
    private checkAndReportViolation;
    private checkViolation;
    private checkNeverOption;
    private checkAlwaysOption;
    private checkAlwaysMultilineOption;
    private checkOnlyMultilineOption;
    private reportViolation;
    private getViolationPosition;
    private createViolationDefect;
    private createViolationFix;
    private checkTrailingCommaViolation;
    private checkObjectBindingPattern;
    private hasConsecutiveCommasInArray;
    private checkArrowFunctionComma;
    private checkArrowParamComma;
    private getArrowFunctionParamInfo;
    private processArrowParamTrailingCommaViolation;
    private reportArrowParamCommaViolation;
    private findMatchingCloseParen;
    private findMatchingCloseAngle;
}
