import { ArkFile } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class EqeqeqCheck implements BaseChecker {
    metaData: BaseMetaData;
    private defaultOptions;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private letDeclarations;
    private fileMatcher;
    private config;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private parseConfig;
    private isBooleanLiteral;
    private getLiteralValue;
    private isTypeOfBinary;
    private isNullCheck;
    private areLiteralsAndSameType;
    private inferType;
    private isSameType;
    private getOperatorRange;
    private isPropertyAccessWithNullUndefined;
    private isUndefinedIdentifier;
    private isComplexPropertyAccessCheck;
    private checkSpecialCases;
    private checkPropertyAccessWithNullUndefined;
    private checkComplexPropertyAccess;
    private shouldSkipCheck;
    private isSmartMode;
    private shouldHandleNullCase;
    private isEqualityCheck;
    private getExpectedOperator;
    private getAllLetDeclarations;
    private checkEqeqeq;
    private createIssue;
    private getDeclarationForIdentifier;
    private isUninitializedLetVariable;
    private findVariableDeclaration;
    private createFix;
    private addIssueReport;
}
