import { ArkFile, ts } from "arkanalyzer";
import { BaseChecker, BaseMetaData, MatcherCallback } from '../../Index';
import { Defects } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { IssueReport } from '../../model/Defects';
export declare class MemberDelimiterStyleCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private issueMap;
    private multilineDetection;
    private interfaceMultilineDelimiter;
    private interfaceMultilineRequireLast;
    private interfaceSingleLineDelimiter;
    private interfaceSingleLineRequireLast;
    private typeLiteralMultilineDelimiter;
    private typeLiteralMultilineRequireLast;
    private typeLiteralSingleLineDelimiter;
    private typeLiteralSingleLineRequireLast;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    private parseOptions;
    private applyDefaultOptions;
    private applyOverrides;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFile, aNode: ts.Node): void;
    private checkInterfaceMembers;
    private getLineInfo;
    private processMember;
    private checkSingleLineLastMember;
    private checkSingleLineMember;
    private checkMultilineLastMember;
    private checkMultilineMember;
    private checkDelimiter;
    private removeDelimiterIfPresent;
    private removeDelimiter;
    private replaceDelimiter;
    private checkTypeAliasMembers;
    private processTypeAliasMembers;
    private getLineInfoType;
    private processMemberType;
    private checkSingleLineLastMemberType;
    private checkSingleLineMemberType;
    private checkMultilineLastMemberType;
    private checkMultilineMemberType;
    private checkDelimiterType;
    private removeDelimiterIfPresentType;
    private removeDelimiterType;
    private replaceDelimiterType;
    private getStartLine;
    private getEndLine;
    private getPositionInfo;
    private addIssueReport;
    private reportSortedIssues;
}
