import { ArkFile, ts } from "arkanalyzer";
import { BaseChecker, BaseMetaData, MatcherCallback } from '../../Index';
import { Defects } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { IssueReport } from '../../model/Defects';
export declare class MethodSignatureStyleCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private issueMap;
    private optionsStyle;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFile, aNode: ts.Node): void;
    private checkInterfaceMembers;
    private buildNameList;
    private handleMethodSignature;
    private processLastDuplicateMethod;
    private collectDuplicatesMethodBody;
    private extractMethodBody;
    private processDuplicateMethod;
    private processUniqueMethod;
    private handlePropertySignature;
    private reportIssue;
    private replaceFirstOccurrence;
    private replaceMethodFirstOccurrence;
    private replaceLastOccurrence;
    private replaceMethodLastOccurrence;
    private findDuplicateNamesWithIndices;
    private checkTypeAliasMembers;
    private buildNameListForTypeAlias;
    private handleTypeAliasMethodSignature;
    private processLastDuplicateTypeAliasMethod;
    private collectTypeAliasDuplicatesMethodBody;
    private extractTypeAliasMethodBody;
    private processDuplicateTypeAliasMethod;
    private processUniqueTypeAliasMethod;
    private handleTypeAliasPropertySignature;
    private reportTypeAliasIssue;
    private getFileExtension;
    private addIssueReport;
    private reportSortedIssues;
}
