import { ArkFile } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class NoConfusingVoidExpressionCheck implements BaseChecker {
    metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private defaultOptions;
    private config;
    private fileMatcher;
    private VOID_FUNCTION_PATTERNS;
    private readonly INVALID_ANCESTOR_TYPES;
    private functionDeclarations;
    private arrowFunctions;
    private classMethods;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private collectFunctionDefinitions;
    private getFunctionName;
    private checkNewPromise;
    private checkSyncResolve;
    private checkPromiseExecutor;
    private checkArrowFunction;
    private checkClassDeclaration;
    private checkVoidExpressions;
    private processLocalFunc;
    private isDotChainDepthnMoreDepth;
    private isParentVoidOrReturn;
    private checkTaggedTemplate;
    private isInsideExpression;
    private isInsideReturnStatement;
    private isFunctionReturningVoid;
    private checkIifeWithCall;
    private functionHasReturnValue;
    private isVoidTypeExpression;
    private hasOptionalChain;
    private checkInvalidContext;
    private specialExpression;
    private isLastStatementInFunction;
    private generateFixCode;
    private returnStatementFixCode;
    private getConditionVariable;
    private getIdentifierFromBinaryExpression;
    private isVariableUndefined;
    private findVariableDeclaration;
    private checkDeclarationName;
    private selectMessageId;
    private checkClassHeritage;
    private checkSuperCall;
    private checkComputedProperty;
    private markVoidExpression;
    private createIssue;
    private createFix;
    private addIssueReport;
    private handleLogical;
    private isLogicalOperator;
    private checkReturnStatement;
    private isWrappedByVoid;
    private isWrappedByExplicitVoid;
    private isExplicitVoid;
    private shouldSkipFunctionCheck;
    private findInvalidAncestor;
    private handleConditionalExpression;
    private skipSpecificPatterns;
    private checkVoidZero;
    private isAllowedVoidContext;
    private isVoidExpressionWithZero;
    private isCoalesceExpression;
    private isLogicalExpression;
    private handlePrefixUnaryExpression;
    private isInvalidAncestorType;
    private handleInvalidAncestorType;
}
