import { ArkFile } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from "../../matcher/Matchers";
import { Rule } from "../../model/Rule";
export declare class NoDynamicDeleteCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private fileMatcher;
    private classMatcher;
    private methodMatcher;
    registerMatchers(): MatcherCallback[];
    private issueMap;
    check: (targetField: ArkFile) => void;
    private getFileExtension;
    private processNonEtsFile;
    private findDeleteExpressions;
    private processMatchingExpressions;
    private reportSortedIssues;
    private processSingleExpression;
    private dynamicDeletePattern;
    private processMatchingVariables;
    private getDeletePropertyPosition;
    private getSourceFile;
    private traverseAST;
    private handleDeleteExpression;
    private processElementAccess;
    private calculateFixPosition;
    private handleComplexFixCase;
    private reportAndCreateFix;
    private getPropertyNameStart;
    private getPositionInfo;
    private extractPropertyKeysFromDeleteExpressions;
    private createAlphabeticChecker;
    private processDeleteExpression;
    private handleElementAccess;
    private handleComplexExpression;
    private strictArrayPattern;
    private handleSpecialPrefix;
    private createTraverseHandler;
    checkVariableName(targetField: ArkFile): string[];
    private deepTraverse;
    private ruleFix;
    private handleStringLiteral;
    private handleIdentifier;
    private getLineAndColumn;
    private addIssueReport;
}
