import { ts, ArkFile } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from "../../matcher/Matchers";
import { Rule } from "../../model/Rule";
export declare class NoExtraParensCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    sourceFile: ts.SourceFile;
    filePath: string;
    private fileMatcher;
    private classMatcher;
    private methodMatcher;
    registerMatchers(): MatcherCallback[];
    check: (file: ArkFile) => void;
    private getPrecedence;
    private isLeftAssociative;
    private checkUnnecessaryParentheses;
    private visit;
    private detectExtraParensType;
    private isRedundantIIFEWrapping;
    private checkDoubleWrappedCall;
    private checkTripleWrappedFunction;
    private checkTripleWrappedFunction7;
    private checkTripleWrappedFunction6;
    private checkTripleWrappedFunction5;
    private checkTripleWrappedFunction4;
    private checkTripleWrappedFunction3;
    private checkTripleWrappedFunction2;
    private checkTripleWrappedFunction1;
    private isWrappedFunction;
    private isAssignmentExpression;
    private isConditionExpression;
    private isConditionalAssign;
    private isConditionalAssign2;
    private isConditionalAssign1;
    private isReturnAssign;
    private isNestedBinaryExpressions;
    private isNestedBinaryExpressions12;
    private isNestedBinaryExpressions11;
    private isNestedBinaryExpressions10;
    private isNestedBinaryExpressions9;
    private isNestedBinaryExpressions8;
    private isNestedBinaryExpressions7;
    private isNestedBinaryExpressions6;
    private isNestedBinaryExpressions5;
    private isNestedBinaryExpressions4;
    private isNestedBinaryExpressions3;
    private isNestedBinaryExpressions2;
    private isNestedBinaryExpressions1;
    private isTernaryOperandBinaryExpressions;
    private isJSXMultiLine;
    private isJSXSingleLine;
    private isEnforceForArrowConditionals;
    private isEnforceForSequenceExpressions;
    private isCommaExpression;
    private isEnforceForNewInMemberExpressions;
    private isEnforceForFunctionPrototypeMethods;
    private isAllowParensAfterCommentPattern;
    private addIssueReport;
}
