import { ArkFile, ts } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class NoExtraBooleanCastCheck implements BaseChecker {
    metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private defaultOptions;
    private fileMatcher;
    private sourceFile;
    private arkFile;
    private enforceForLogicalOperands;
    static readonly binaryExpressionTypes: ts.SyntaxKind[];
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private getUnwrappedExpression;
    private hasRedundantBooleanCast;
    private hasCheckPrefixUnaryExp;
    private isInBooleanContext;
    private isParentLogicalExpression;
    private addIssue;
    private getInnermostNonBooleanArg;
    private checkNode;
    private checkExtraBooleanCast;
    private checkPrefixUnaryExpression;
    private checkNewCallExpression;
    private checkCallExpressionOneArguments;
    private checkCallExpressionNoOneArguments;
    private isBooleanTypeExpression;
    private canSafeFix;
    private isValidBooleanCall;
    private checkArgumentSafety;
    private hasComments;
    private checkPrecedenceSafety;
    private needsParentheses;
    private getPrecedence;
    private getContextualPrecedence;
    private createFix;
    private addIssueReport;
}
