import { ArkFile } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class NoFloatingPromisesCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private errorPositions;
    private useMethods;
    private globalArkFile;
    private globalArkCls;
    private fileMatcher;
    private promiseTypeCache;
    private statementCache;
    private promiseCache;
    private unhandledPromiseCache;
    private maxDepth;
    private processedTypes;
    private recursionCount;
    private resetCaches;
    private checkAndIncreaseRecursion;
    private decreaseRecursion;
    private getTypeKey;
    registerMatchers(): MatcherCallback[];
    private getOption;
    private isAsyncIife;
    private getRejectionHandlerFromThenCall;
    private hasValidRejectionHandler;
    private getObjectFromFinallyCall;
    private isValidCatchHandler;
    private isValidThenHandler;
    private isFunctionType;
    private getRejectionHandlerFromCatchCall;
    private report;
    private getErrorMessage;
    private checkArrayLiteralExpression;
    private checkCommaBinaryExpression;
    private getConditionalValue;
    private checkConditional;
    private isUnhandledPromise;
    private _determineUnhandledPromise;
    private checkAwaitExpression;
    private checkArrayExpression;
    private checkNodeIsPromise;
    private checkNormalBinop;
    private checkNormalBinopLeftValue;
    private checkQueryValueStmt;
    private checkQueryBySeekIndex;
    private checkQueryValue;
    private preCheck;
    private checkExpr;
    private isInVildNode;
    private checkIsPromise;
    private checkFieldRef;
    private checkFieldRefIsPromise;
    private isPromise;
    private _determineIsPromise;
    private _checkStaticInvokeExpr;
    private checkPrtIsPromise;
    private isPsArray;
    private _determineIsPsArray;
    private _checkGenericPsArray;
    private _checkUnionPsArray;
    private _checkAliasPsArray;
    private _checkIntersectionPsArray;
    private _checkUnclearReferencePsArray;
    private typesIsPromiseArray;
    private isPromiseArray;
    private getNode;
    private isNumericUsingIsNaN;
    private checkIsCustemClsPromise;
    private checkIsPromiseCls;
    private isPromiseType;
    private _determinePromiseType;
    private _checkTypesCollection;
    private _checkTupleType;
    private _checkAliasType;
    private _checkFunctionType;
    private isPromiseLike;
    private checkMethod;
    private checkClass;
    private checkStmt;
    check: (target: ArkFile) => void;
    private addIssueReport;
}
