import { ArkMethod } from 'arkanalyzer';
import { MatcherCallback } from '../../matcher/Matchers';
import { Defects, IssueReport } from '../../model/Defects';
import { Rule } from '../../model/Rule';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
export declare class NoImpliedEvalCheck implements BaseChecker {
    defects: Defects[];
    issues: IssueReport[];
    readonly metaData: BaseMetaData;
    rule: Rule;
    private buildMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkMethod: ArkMethod) => void;
    private handleArkInvokeStmt;
    private handleInvalidArgs;
    private handleFunctionConstructorInInvoke;
    private handleArkAssignStmt;
    private isValidFunctionCall;
    private handleInstanceInvokeInAssign;
    private handleStaticInvokeInAssign;
    private filterEvalLikeMethods;
    private hasGlobalCandidate;
    private hasEvalLikeMethod;
    private shouldSkipInvokeExpression;
    private hasInvalidArgsTypes;
    private isValidBinopExpr;
    private handleUnknownType;
    private handleBaseUnknownType;
    private handleInstanceFieldRef;
    private checkInitializerForFunctionType;
    private checkFields;
    private checkBase;
    private handlePtrInvokeExpr;
    private isReturnTypeFunctionType;
    private isFunctionType;
    private isFunctionConstructor;
    private checkTypeAst;
    private checkMethodDeclaration;
    private getValueAst;
    private addIssueReport;
    private getLineAndColumn;
}
