import { ts, ArkFile, Value, Local, Type, ArkClass, Stmt, ArkMethod } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
interface ChecksVoidReturnOptions {
    arguments?: boolean;
    attributes?: boolean;
    properties?: boolean;
    returns?: boolean;
    variables?: boolean;
}
export declare class NoMisusedPromisesCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private fileMatcher;
    private globalArkCls;
    private globalArkFile;
    private globalArkMethod;
    private globalNode;
    private globalStmt;
    private useMethods;
    private errorPositions;
    private visitedNodes;
    private typeCache;
    private methodCache;
    private readonly MAX_RECURSION_DEPTH;
    registerMatchers(): MatcherCallback[];
    private getOption;
    private getNodeKey;
    private getTypeKey;
    private getMethodKey;
    private getMethodWithCache;
    private checkIsPromise;
    private handleUnknownType;
    private checkDeclarationStatement;
    private isPromiseType;
    private checkTypeForPromise;
    private checkFunctionTypeForPromise;
    private getExpressionNode;
    private checkConditional;
    private handleIfStatement;
    private handleAssignStatement;
    private isValidBinaryExpression;
    private handleParenthesizedExpression;
    private handleLocalVariable;
    private handleUnaryExpression;
    private handleConditionExpression;
    private handleBinaryExpression;
    private handlePromiseLikeExpression;
    private isControlStatement;
    private isVariableDeclaration;
    private getVariableDeclarationNode;
    private isTestExprForBinaryExpression;
    report(messageId: string, node: ts.Node): void;
    private checkIsPromiseCls;
    private checkIsCustemClsPromise;
    private isPromise;
    private checkAbsArkIsPromise;
    private checkFieldRef;
    private checkFieldRefIsPromise;
    isPromiseLike(value: Value | Stmt, node: ts.Node, cls?: ArkClass | null, depth?: number): boolean;
    private isInVildNode;
    private checkPrtIsPromise;
    checkNoMisusedPromises(stmt: Stmt): void;
    getArgumentsPtrFunction(type: Type, count?: number): ArkMethod | null;
    checkGetDeclarStmt(declarName: string): Stmt | null;
    private findDeclarationInStmts;
    private handleAssignStmt;
    private handleInvokeExpr;
    private handleSpreadElement;
    private getParamType;
    private checkArgumentType;
    private processInvokeExpr;
    checkArguments(stmt: Stmt | Value, node: ts.CallExpression | ts.NewExpression): void;
    isVoidType(type: Type): boolean;
    checkProperty(stmt: Value | Stmt, node: ts.Node): void;
    private handleReturnStatement;
    private getPropertyTypes;
    private getPropertyName;
    private handlePropertyAssignment;
    private handleShorthandPropertyAssignment;
    private handleMethodDeclaration;
    getDeclarByName(propertyName: string): Type | ArkMethod | null;
    checkReturnType(op: Local, node: ts.ReturnStatement): boolean;
    checkReturnStatement(stmt: Stmt | Value, node: ts.Node): void;
    checkAssignment(stmt: Stmt | Value, node: ts.BinaryExpression | ts.VariableDeclaration): void;
    checkVariableDeclarations(stmt: Stmt | Value, node: ts.Node): void;
    checkVariableAssignments(stmt: Stmt | Value, node: ts.Node): void;
    checkVoidReturn(stmt: Stmt | Value, node: ts.Node, checksVoidReturn: ChecksVoidReturnOptions): void;
    leftVoidReturn(left: Local): boolean;
    checkSpread(stmt: Stmt | Value, node: ts.Node): void;
    checkTsNodeIsPromise(node: ts.Node): boolean;
    checkMethod(arkMethod: ArkMethod): void;
    checkClass(arkCls: ArkClass): void;
    checkFile(arkFile: ArkFile): void;
    check: (target: ArkFile) => void;
    private sortAndReportErrors;
    private addIssueReport;
}
export {};
