import { ArkFile } from 'arkanalyzer';
import { Rule } from '../../Index';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects } from '../../Index';
import { MatcherCallback } from '../../Index';
import { IssueReport } from '../../model/Defects';
export declare class NoRestrictedSyntaxCheck implements BaseChecker {
    issues: IssueReport[];
    rule: Rule;
    defects: Defects[];
    private defaultOptions;
    metaData: BaseMetaData;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (targetField: ArkFile) => void;
    private getDefaultOption;
    private addIssueReport;
    private checkRestrictedSyntax;
    private checkArrayLiteralTildeOperator;
    private findTildeOperatorRule;
    private addErrorForTildeOperator;
    private checkNodeAgainstRules;
    private shouldSkipNodeCheck;
    private addErrorForMatchedRule;
    private getTargetNodeForError;
    private getErrorStartPosition;
    private checkAttribute;
    private checkSpecialCases;
    private getValueForAttribute;
    private getBinaryExpressionOperator;
    private traversePath;
    private compareValues;
    private compareNumericValues;
    private matchRule;
    private handleSpecialRuleMatching;
    private matchChainExpression;
    private matchNodeWithAttributes;
    private matchNthChild;
    private matchOptionalChain;
    private matchStandardRule;
    private matchCurrentNode;
    private matchRuleForFunctionDeclaration;
    private findDeepestRule;
    private checkNodeAgainstFunctionRule;
    private checkFunctionParameters;
    private compareParameterLength;
    private eslintToTsNodeMap;
    private normalizeOptions;
    private parseRule;
    private handleSpecialRule;
    private handleCallExpressionRule;
    private parseStandardRule;
    private processSelectorPart;
    private createParsedRule;
    private parseSelectorPart;
    private handleSpecialSelectors;
    private parseAttributeOnlySelector;
    private parseRegularSelector;
    private normalizeTypePart;
    private parseAttributes;
    private parseRegularAttributes;
    private parseValue;
}
