import { ArkFile, ts } from 'arkanalyzer';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects } from '../../Index';
import { MatcherCallback } from '../../Index';
import { Rule } from '../../Index';
import { IssueReport } from '../../model/Defects';
export declare class NoRedeclareCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private readonly defaultTypes;
    private builtinGlobals;
    private ignoreDeclarationMerge;
    private readonly globalKeyword;
    private readonly globalsKeyword;
    private readonly keywordList;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (targetFile: ArkFile) => void;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFileLike, aNode: ts.Node): void;
    private checkBlockRedeclare;
    private checkImportRedeclare;
    private checkSyntaxListRedeclare;
    private getSpecifyChild;
    private checkRedeclare;
    private checkRedeclareInMembers;
    private checkBuiltIn;
    private checkNodeInBlock;
    private checkRedeclareInNodes;
    private isNodeChecked;
    private objectNeedCheck;
    private objectNeedCheckContinuous;
    private getVariableDeclarationListNode;
    private getBindNameNodeMember;
    private getImportEqualsDeclarationNode;
    private getFunctionNodes;
    private getImportDeclarationNodes;
    private getImportNodes;
    private getVariableStatementNodes;
    private getArrayBindingPatternNode;
    private getIfNodes;
    private getIfNodesImplement;
    private getWhileNodesImplement;
    private getForNodes;
    private getForStatementNodes;
    private getSwitchCaseNodes;
    private getCaseOrDefaultClauseNodes;
    private getSyntaxListNodes;
    private isBuiltinKeyword;
    private needCheckIgnoreDeclarationMerge;
    private checkGlobals;
    private getCommonList;
    private handleExpressStatement;
    private handleBinaryExpression;
    private getLabeledStatement;
    private getLeftSpace;
    private isGlobal;
    private handleCommonListList;
    private compareCommon;
    private getBinaryExpressionChildren;
    private getNodePosition;
    private addGlobalNode;
    private getComments;
    private addIssueReport;
}
