import { ArkFile } from "arkanalyzer";
import { BaseChecker, BaseMetaData, MatcherCallback } from '../../Index';
import { Defects } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { IssueReport } from '../../model/Defects';
export declare class NoThrowLiteralCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private allowThrowingAny;
    private allowThrowingUnknown;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    private loopNode;
    private processThrowAST;
    private handleThrowStatementInBlock;
    private checkCatchClauseThrowExpression;
    private handlePropertyAccessExpression;
    private getClassNameFromExpression;
    private findVariableDeclaration;
    private handleCallExpression;
    private findFunctionDeclaration;
    private handleIdentifier;
    private checkVariableDeclarations;
    private processVariableDeclarationByName;
    private checkDeclarationInitializer;
    private checkAsExpression;
    private checkDeclarationType;
    private checkNewExpression;
    private checkFunctionParameters;
    private checkParameterType;
    private checkUndefined;
    private handleNewExpression;
    private checkClassDeclaration;
    private handleOtherExpressions;
    private isCommonKind;
    private getPositionInfo;
    private addIssueReport;
}
