import { Rule } from '../../model/Rule';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { ArkFile } from 'arkanalyzer';
import { Defects, MatcherCallback } from '../../Index';
import { IssueReport } from '../../model/Defects';
export declare class NoUnnecessaryBooleanLiteralCompareCheck implements BaseChecker {
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    metaData: BaseMetaData;
    private fileMatcher;
    private defaultOptions;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private checkBooleanComparisons;
    private checkBinaryExpression;
    private isTrue;
    private booleanBooleanLiteral;
    private instanceOfBooleanLiteral;
    private otherExpression;
    private isnullBoolean;
    private isNullableBooleanFix;
    private declareBooleanType;
    private declareBooleanTypeFix;
    private isComparisonOperator;
    private getText;
    private findBooleanLiteral;
    private findSymbolDeclaration;
    private findInSourceFileStatements;
    private findVariableDeclarationInStatements;
    private findVariableDeclarationInStatement;
    private findVariableDeclarationInDeclarationList;
    private isMatchingVariableDeclaration;
    private addDefect;
    private isInGenericContext;
    private isInArrowFunctionContext;
    private hasGenericType;
    private hasGenericAncestor;
    private isBooleanLiteralLike;
    private isNullableBooleanType;
    private createFix;
}
