import { ArkFile } from 'arkanalyzer';
import { Rule } from '../../Index';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects } from '../../Index';
import { MatcherCallback } from '../../Index';
import { IssueReport } from "../../model/Defects";
export declare class NoUnreachableCheck implements BaseChecker {
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    metaData: BaseMetaData;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    private checkControlFlowStatement;
    private checkNextStatementAfterControlFlow;
    private addControlFlowError;
    private checkUnreachableCode;
    private preprocessArrowFunctions;
    private processArrowFunctionBody;
    private processArrowFunctionBlockBody;
    private checkSwitchStatementInArrowFunction;
    private hasSwitchTerminatingDefault;
    private checkUnreachableStatementAfterSwitch;
    private isUnreachableStatementCandidate;
    private checkControlFlowTerminationInArrowFunction;
    private addUnreachableErrorForStatement;
    private visitAST;
    private processNodeByType;
    private isControlFlowEndingStatement;
    private checkOtherNodeTypes;
    private isFunctionNode;
    private isLoopNode;
    private checkInfiniteForLoop;
    private isFunctionBodyTerminated;
    private checkConditionalExpression;
    private unwrapParentheses;
    private markIfBlockUnreachable;
    private addUnreachableCodeError;
    private checkIfStatement;
    private checkNextStatementAfterIf;
    private addUnreachableError;
    private checkSourceFileStatements;
    private isOnlySwitchOrSimpleExpressions;
    private shouldSkipStatement;
    private isFlowTerminatingStatement;
    private processUnreachableStatement;
    private isStatementAfterClass;
    private reportUnreachableStatement;
    private checkFunctionBody;
    private checkFunctionStatements;
    private infiniteForLoopHasBreak;
    private checkNextFunctionStatement;
    private checkLoopStatement;
    private checkLoopBody;
    private checkUnreachableLoopStatement;
    private checkClassDeclaration;
    private checkClassExtends;
    private checkClassConstructor;
    private findConstructorIndex;
    private isStaticProperty;
    private isInstanceProperty;
    private reportUnreachableField;
    private checkFieldsInRange;
    private checkUnreachableInstanceFields;
    private checkTryStatement;
    private isInAsyncFunction;
    private hasOnlyThrowStatement;
    private checkCatchBlockReachability;
    private checkNextStatementAfterTry;
    private checkFinallyBlock;
    private checkSwitchStatement;
    private isVarDeclarationStmt;
    private findNextStatement;
    private isControlFlowTerminated;
    private isBasicControlFlowTerminator;
    private isComplexControlFlowTerminator;
    private checkSwitchTermination;
    private checkCaseClauseTermination;
    private checkInfiniteWhileLoop;
    private checkInfiniteWhileLoopBlock;
    private hasSuperCallInConstructor;
    private isBreakOrContinue;
    private checkUnreachableSemicolons;
    private checkUnreachableSemicolonsInArrowFunction;
    private checkSwitchWithTerminatingDefault;
    private findDefaultClause;
    private hasTerminatingStatement;
    private markStatementAsUnreachable;
    private preprocessConditionalExpression;
    check: (targetField: ArkFile) => void;
    private sortMyInvalidPositions;
    private addIssueReport;
    private isExportStatement;
}
