import { ArkFile } from "arkanalyzer";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { MatcherCallback } from '../../Index';
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
export declare class NoUnnecessaryTypeAssertionCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private options;
    private asRoot;
    private filePath;
    private symbolTable;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private buildSymbolTable;
    private checkTypeAssertion;
    private checkExpression;
    private getConstrainedTypeOfArkAssignStmt;
    private checksNonNullExpression;
    private addUnnecessaryAssertion;
    private addNonNullExpression;
    private checkNestedNonNullExpression;
    private checkParenthesizedNonNullExpression;
    private checkOptionalChainingWithNonNull;
    private isNullableExpression;
    private isNullableIdentifier;
    private isNullableIdentifierOther;
    private isPropertyAfterOptionalChain;
    private isOptionalParameterNonNullAssertion;
    private isParameterOptional;
    private isParameterOptionalIdentifier;
    private isParameterOptionalBindingPattern;
    private checkAllTypesOfNonNullAssertions;
    private checkAllTypesOfNonNullAssertionsIdentifier;
    private isOptionalParameterWithChaining;
    private findParameterInfoDeclaration;
    private findParameterInfoDeclarationParam;
    private findParameterInfo;
    private findVariableDeclarationInfo;
    private infoHasLiteralInitializer;
    private ruleFix;
    private addIssueReportNodeFix;
}
