import { ArkMethod, ArkFile, ts } from "arkanalyzer";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { MatcherCallback } from "../../matcher/Matchers";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
export declare class NoUnsafeArgumentCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private clsMatcher;
    private buildMatcher;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    checkArk: (arkFile: ArkFile) => void;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFile, aNode: ts.Node): void;
    private findArrowFunction;
    private findFunctionDeclaration;
    private findClassDeclaration;
    private checkArgumentType;
    private checkNewExpression;
    private checkArrowFunctionParameters;
    private checkThisKeywordPropertyAccess;
    private checkCallExpressionArguments;
    private checkVariableStatementsForArguments;
    private checkVariableDeclarationsForArguments;
    private checkFunctionDeclarationParameters;
    private checkFunctionDeclarationParametersForArrayTypes;
    private checkUnionTypeNodeForArrayType;
    private checkVariableStatementsForIncludesOrIndexOf;
    private isValidVariableDeclarationType;
    private checkArgumentsForIssueReport;
    private checkTestMethodArguments;
    private isArgumentDefinedInVariableStatements;
    private handlePropertyAccessExpression;
    private checkArkCallExpression;
    private checkRegExpArguments;
    check: (targetMethod: ArkMethod) => void;
    private checkInvokeArguments;
    private checkLocalTypeForAny;
    private handleExtendedParameter;
    private getFileExtension;
    private getPositionInfo;
    private addArkIssueReport;
    private addIssueReport;
    private getLineAndColumn;
}
