import { ArkFile, ts } from "arkanalyzer";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { MatcherCallback } from "../../matcher/Matchers";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
export declare class NoUnsafeCallCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFile, aNode: ts.Node): void;
    private checkFunctionDeclaration;
    private handleExpressionStatement;
    private handleCallExpression;
    private handleNewExpression;
    private handleTaggedTemplateExpression;
    private checkParameter;
    private checkPropertyAccessParameter;
    private checkParameterType;
    private handleTaggedTemplate;
    private findVariableDeclaration;
    private checkExpressionStatement;
    private extractExpressionInfo;
    private checkVariableDeclaration;
    private findLastParent;
    private getClassNameFromExpression;
    private getNameFromExpression;
    private getLastExpression;
    private checkDeclarationType;
    private checkTypeLiteralMembers;
    private getPositionInfo;
    private addAstIssueReport;
    private findIdentifier;
    private findParenthesizedExpression;
    private findClassDeclaration;
    private findFunction;
    private findArrowFunction;
    private findNewExpression;
    private handleUnsafeCallExpression;
    private handleParenthesizedExpression;
    private handleConditionalExpressionWithPropertyAccess;
    private handleIdentifierMethod;
    private handlePropertyAccessExpression;
    private checkReduceMethodWithImport;
    private handleSuperAndThisKeyword;
    private handleArrayAndNumberCall;
    private handleReturnAndNewExpression;
    private isFunctionDefinedInBlock;
    private isFunctionDefinedInVariableStatement;
    private checkParameterForUnsafeCall;
    private checkVariableDeclarationForUnsafeCall;
    private checkVariableDeclarationsForUnsafeCall;
    private checkFunctionBodyForUnsafeCall;
    private checkFunctionDeclarationForUnsafeCall;
    private checkFunctionDefinition;
    private checkVariableDeclarationForAnyAndRequire;
    private checkVariable;
    private checkVariableDeclarationConditions;
    private checkRegularExpressionInitializer;
    private checkObjectLiteralProperties;
    private checkNewExpressionParameters;
    private checkVariableInitializerConditions;
    private checkHintNameInSourceFile;
    private checkHintNameConditions;
    private findVariableDeclarationForFunction;
    private isFunctionDefinedInClassOrBlock;
    private checkVariableDeclarationForFunction;
    private handleFunctionCallChecks;
    private handleCallExpressionChecks;
    private isBuiltInOrImportedObject;
    private checkUndefinedFunctionCall;
    private getUnsafeCallMessage;
    private isKeyMethod;
    private isRegularExpression;
    private isBuiltInObject;
}
