import { ArkFile, ts } from "arkanalyzer";
import { BaseChecker, BaseMetaData } from "../../checker/BaseChecker";
import { MatcherCallback } from "../../matcher/Matchers";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
export declare class NoUnsafeMemberAccessCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (arkFile: ArkFile) => void;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFile, aNode: ts.Node): void;
    private findArrowFunction;
    private findFunction;
    private findClassDeclaration;
    private getExpressionName;
    private checkFunctionParameter;
    private findDeclarationListElement;
    private isComplexPropertyAccess;
    private findNumericOrStringLiteralDeclaration;
    private checkElementAccessExpression;
    private getVariableName;
    private isStringFromCharCodeImport;
    private shouldSkipCheck;
    private isArrowFunctionWithMethodCall;
    private checkFunctionBodyForUnsafeMemberAccess;
    private checkFunctionDeclarationForUnsafeMemberAccess;
    private checkExpressionAccess;
    private checkTypeLiteralMember;
    private checkVariableTypeConditions;
    private isNestedBinaryExpression;
    private checkVariableDeclaration;
    private findDeclarationListElementNode;
    private handleUnsafeMemberAccess;
    private processSourceFileStatements;
    private handleCallExpression;
    private checkNonNullExpression;
    private handleParenthesizedExpression;
    private handleThisKeyword;
    private setHintElementAndPositionInfo;
    private hasParameterWithDefinedType;
    private checkPropertyAccessExpression;
    private handleElementAccessExpression;
    private getPositionInfo;
    private addArkIssueReport;
    private isKeyMethod;
    private isUnknownStats;
    private isBuiltInObject;
}
