import { ArkMethod, ts, ArkFile } from "arkanalyzer";
import { MatcherCallback } from "../../matcher/Matchers";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { BaseChecker, BaseMetaData } from "../../checker/BaseChecker";
export declare class NoUnsafeReturnCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private regex;
    private clsMatcher;
    private buildMatcher;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    checkArk: (arkFile: ArkFile) => void;
    loopNode(targetFile: ArkFile, sourceFile: ts.SourceFile, aNode: ts.Node): void;
    private shouldSkipArrowFunctionCheck;
    private shouldSkipArrowFunctionCheckForArrayMethods;
    private checkArkArrowFunction;
    private checkArrowFunctionBodyType;
    private checkThisKeywordInConstructor;
    private checkArrowFunctionBody;
    private findClassDeclarationParentRecursive;
    private checkPropertyAccessExpressionWithThisKeyword;
    private checkIdentifierReturnStatement;
    private checkIdentifierExpression;
    private checkArrayTypeNode;
    private checkElementAccessExpressionForArrayType;
    private checkElementAccessExpressionForUndefinedType;
    private checkElementAccessExpression;
    private checkIdentifierExpressionForTypeLiteral;
    private checkNonNullExpressionForTypeLiteral;
    private checkElementAccessExpressionForIdentifier;
    private checkArkReturnStatement;
    private checkReturnExpression;
    private checkCallAndElementAccessExpression;
    private checkCallExpression;
    private checkBlockAndFunction;
    private checkParentCallExpression;
    private checkStatementsForParamName;
    check: (targetMethod: ArkMethod) => void;
    private checkReturnStatementBlock;
    private isAllowedClassType;
    private isUnionType;
    private checkReturnStatement;
    private checkExpressionStatement;
    private analyzeReturnStmt;
    private checkReturnType;
    private checkReturnOrExpressionStatement;
    private checkUnknownBeforeBrace;
    private getFileExtension;
    private addIssueReport;
    private getPositionInfo;
    private addArkIssueReport;
    private getLineAndColumn;
}
