import { ArkClass } from 'arkanalyzer/lib/core/model/ArkClass';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { MatcherCallback } from '../../matcher/Matchers';
import { Defects, IssueReport } from '../../model/Defects';
import { Rule } from '../../model/Rule';
export declare class NoUseBeforeDefineCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private clsMatcher;
    registerMatchers(): MatcherCallback[];
    check: (targetClass: ArkClass) => void;
    private handleRightOp;
    private handleLeftOp;
    private isSpecialABCase;
    private otherAddUsedBefores;
    private forInHandleLeftOp;
    private processVarOrImport;
    private processExpression;
    private processExpressionFieldSignature;
    private processExpressionMethodSignature;
    private processExpressionClassSignature;
    private processExpressionUnknowType;
    private processAbstracFieldRef;
    private filterUnuseds;
    private addIssueReport;
    private getLineAndColumn;
    private getArrayDefineVarIndex;
    private getTextPosition;
    private escapeRegExp;
    private addIssueReportOther;
    private getLineAndColumnOther;
    private getAccuratePosition;
    private extractFunctionName;
    private getFileExtension;
    private processExtendedClasses;
    private processMethod;
    private processVarLocal;
    private processLocalDefType;
    private processGlobal;
    private pushGlobal;
    private processStmt;
    private processArkIfStmt;
    private processArkAssignStmt;
    private processExcClass;
    private execStmts;
    private execPushStmts;
    private processExcField;
    private pushExcField;
    private processInvokeStmt;
    private processInvokeStmtInside;
    private isProcessInvokeStmtInsideMethod;
    private processAbstractInvokeExpr;
    private processAbstractInvokeExprinside;
    private processArkNewExpr;
    private extractBetween;
    private processParams;
    private pushParam;
    private processLocalType;
    private processSticMethod;
    private execSticMethod;
    private pushSticMethod;
    private processExport;
    private getExportSourceLine;
    private processFileUsedIssues;
    private processDefaultMethod;
    private isInImport;
    private pushAllVar;
    private isVariableDeclaration;
    private pushGlobleMap;
}
