import { ArkFile } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { MatcherCallback } from "../../matcher/Matchers";
import { Rule } from "../../model/Rule";
import { Defects, IssueReport } from "../../model/Defects";
export declare class PreferRegexpExecCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private isQuotedStringRege;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private checkForRegExpExec;
    private traverseAST;
    private isMatchCall;
    private processMatchCall;
    private shouldReportIssue;
    private createLocationInfo;
    private isRegExpType;
    private checkRegExpDeclaration;
    private checkRegExpInitializer;
    private checkGlobalFlag;
    private checkFlags;
    private checkFlagsVariable;
    private handleIdentifier;
    private handleCallExpression;
    private handleNewExpression;
    private isRegExpConstructorCall;
    private isRegExpNewExpression;
    private findVariableDeclaration;
    private findInCurrentScope;
    private checkFunctionParameters;
    private checkVariableDeclarations;
    private getParentScope;
    private ruleFix;
    private escapeSlashesInQuotedString;
    private isSlashWrappedString;
    private isQuotedString;
    private getFixRange;
    private isStringType;
    private checkStringDeclaration;
    private resolveTypeAlias;
    private addIssueReportNodeFix;
}
