import { ArkFile, Stmt, ts } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class PreferNullishCoalescingCheck implements BaseChecker {
    private processedStatements;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private defaultOptions;
    metaData: BaseMetaData;
    private options;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (targetField: ArkFile) => void;
    private getStmts;
    private executeCheckWithCachedAST;
    isConditionalExpression(node: ts.ConditionalExpression): boolean;
    private executeCheck;
    private checkConditionalExpression;
    private checkCondition;
    private handleLogicalOr;
    private handleLogicalAnd;
    private handleBasicBinary;
    private validateTestNodes;
    private isMatchingIdentifier;
    private shouldSkipReport;
    isIncludeundefindOrNull(stmt: Stmt): boolean;
    private checkLogicalOrExpression;
    private isTernaryExpression;
    private isNullCheckOperator;
    private isStrictNullCheck;
    private isNull;
    private isUndefinedIdentifier;
    private isSameNode;
    private isMixedLogicalExpression;
    private isConditionalTest;
    private isLogicalNullOrUndefined;
    private checkTypesValid;
    private isRightNotNullOrUndefind;
    private checkTypeIncludesNullUndefined;
    private shouldIgnoreType;
    private addIssueReportForTernaryTests;
    private addIssueReportForConditionalTests;
    private getLineAndColumns;
    private processAllLines;
    private processLine;
}
