import { ArkFile, Stmt, ts, Value } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects, IssueReport } from "../../model/Defects";
import { MatcherCallback } from "../../matcher/Matchers";
import { Rule } from "../../model/Rule";
interface LocationInfo {
    line: number;
    character: number;
    startCol: number;
    endCol: number;
    isStartWith: boolean;
    methodName: string;
    testObjectText?: string;
    textEExpectedStr?: string;
}
export declare class PreferStringStartsEndsWithCheck implements BaseChecker {
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    filePath: string;
    fileSourceFile: ts.SourceFile;
    metaData: BaseMetaData;
    private fileMatcher;
    private stmts;
    private processedLocations;
    private astCache;
    private methodNameCache;
    private stringContextCache;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private initializeCheckContext;
    private collectValidStatements;
    private processValidStatements;
    private shouldCheckStatement;
    private getMethodName;
    private isStringContext;
    private isAllQuotedSegments;
    getObjectExpressionType(stmt: Stmt): string;
    getType(stmt: Stmt | Value, count?: number): string;
    private checkRightOp;
    private checkLeftOp;
    PreferStringStartsEndsWithCheck(string: string, stmt: Stmt): LocationInfo[];
    private getOrCreateAstSourceFile;
    private processCallExpression;
    private processTestMethod;
    private processRegexLiteral;
    private isSimpleStartsWithOrEndsWithPattern;
    private containsComplexRegexSyntax;
    private processRegexVariable;
    private processBinaryExpression;
    private processElementAccessExpression;
    private processLengthMinusOneExpression;
    private processCallExpressionInBinary;
    private processCharAtMethod;
    private processIndexOfMethod;
    private processLastIndexOfMethod;
    private getExpressionValue;
    private getStringInfo;
    private processSliceMethod;
    private getTargetValueAndExpression;
    private processSliceArguments;
    private handleTargetValueDefined;
    private isValidSliceStartAndLength;
    private isValidNegativeSliceLength;
    private handleTargetValueUndefined;
    private isValidSliceStartAndLengthProperty;
    private processSubstringMethod;
    private processSubstringArguments;
    private isValidStartAndLength;
    private isValidNegativeLengthBinary;
    private isValidNegativeLengthUnary;
    private processMatchMethod;
    private getRegexText;
    private processMatchRegex;
    private isStartsWithOrEndsWithCall;
    private getObjectExpression;
    private resolveVariableInitializer;
    private getRightStmt;
    private getArkName;
    private checkLeftOpUsage;
    private findVariableDeclarationInBlock;
    private isLastCharacterCheck;
    private ruleFix;
    private handleTestFix;
    private handleNoNameFix;
    private handleCharAtFix;
    private handleMatchFix;
    private handleSliceFix;
    private changeDoubleQuotesToSingleQuotes;
    private handleSubstringFix;
    private handleIndexOfFix;
    private addIssueReportNodeFix;
    private getLineAndCharacterInfo;
    private createLocationInfo;
    private addResult;
}
export {};
