import { ArkFile } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class PreferConstCheck implements BaseChecker {
    metaData: BaseMetaData;
    private defaultOptions;
    private config;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private scopeStack;
    private ast;
    private currentArkFile;
    private fileMatcher;
    private loopStack;
    private currentLoopParts;
    private allLoopContexts;
    private currentScope;
    private enterScope;
    private exitScope;
    private enterLoop;
    private exitLoop;
    private enterLoopPart;
    private exitLoopPart;
    registerMatchers(): MatcherCallback[];
    private parseConfig;
    check: (target: ArkFile) => void;
    private checkPreferConst;
    private enter;
    private leave;
    private visitVariableDeclaration;
    private visitBinaryExpression;
    private visitForStatement;
    private visitForOfStatement;
    private visitForInStatement;
    private walkNodes;
    private collectReferencesInExpression;
    private checkForStatement;
    private enhancedVisitors;
    private isInConditionContext;
    private isReadAccess;
    private createLoopContext;
    private collectLoopConditionWrites;
    private trackAssignmentTarget;
    private walkForExpression;
    private collectDeclaredVariables;
    private processPatternForContext;
    private collectReadRefs;
    private isWriteAccess;
    private hasReadBeforeAssign;
    private processLetDeclaration;
    private visitVarBindingName;
    private processVarBindingPattern;
    private processVarDeclaration;
    private processBindingPattern;
    private registerVariable;
    private parseAssignmentIsParenthesizedExpression;
    private processAssignment;
    private isReassigned;
    private isVariableInitialized;
    private isInExportAssignment;
    private isVoidZeroInitializer;
    private isVariableInLoop;
    private isObjectLiteral;
    private reportConstSuggestion;
    private shouldSkip;
    private analyzeVariableDeclaration;
    private getDeclarationsAndLoopType;
    private checkUnsafeDestructuring;
    private checkAllInitialized;
    private createFix;
    private createDiagnostic;
    private addIssueReport;
}
