import { ArkMethod } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
import { IssueReport } from '../../model/Defects';
export declare class RestrictPlusOperandsCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private left;
    private right;
    private type;
    private stringLike;
    private warnLeftOp;
    private operands;
    private messageId;
    private get messages();
    private fileMatcher;
    private classMatcher;
    private methodMatcher;
    registerMatchers(): MatcherCallback[];
    check: (method: ArkMethod) => void;
    private getOptions;
    private processStatement;
    private handleBinaryOperation;
    private processPlusOperandTypes;
    private editBigIntType;
    private getGlobalType;
    private extractPlusOperands;
    private extractEqualRightValue;
    private getTypeString;
    private getStringLike;
    private isBigIntLiteral;
    private isBigIntType;
    private isValidType;
    private checkTypeCombo;
    private checkNumberTypeCombo;
    private isNumberType;
    private typeDifferent;
    private checkBasicTypes;
    private checkTypeAndReport;
    private isNullish;
    private checkNumberStringCombo;
    private isStringNumberCombo;
    private checkBigintNumberCombo;
    private isBigintNumberCombo;
    private checkCustomTypes;
    private checkNullishTypes;
    private checkRegExpType;
    private addIssueReport;
    private getLineAndColumn;
    private getTextIndex;
    private clear;
}
