import { ArkFile, Stmt, ts } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
import { IssueReport } from '../../model/Defects';
import { RuleFix } from '../../model/Fix';
interface LocationInfo {
    line: number;
    character: number;
    startCol: number;
    endCol: number;
    returnString: string;
    testObjectText?: string;
}
export declare class ReturnAwaitCheck implements BaseChecker {
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    metaData: BaseMetaData;
    private fileMatcher;
    private defaultOptions;
    private promiseTypeCache;
    private ancestorCache;
    private asyncFunctions;
    private returnStatements;
    private declarationCache;
    private tryStmts;
    private catchStmts;
    private norStmts;
    private filePath;
    private sourceFile;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private resetCheckerState;
    private processClassMethods;
    private processMethodStatements;
    private collectAllAsyncFunctions;
    private analyzeAllAsyncFunctions;
    private collectAsyncFunctions;
    private collectDeclarations;
    private collectReturnStatements;
    private analyzeFunction;
    private containsAwait;
    private testReturnStatement;
    private alwaysOption;
    private NeverOption;
    private inTryCatch;
    private isInTryCatch;
    private isPromiseType;
    private isVarReturnPro;
    private checkTernary;
    private TernayString;
    private getTernayString;
    private checkMethodType;
    private getRelatedMethods;
    private checkMethodModifier;
    private checkLocalReturn;
    private checkAwaitReturn;
    getDlears(declare: Stmt, depth?: number): string;
    private handleExpressionType;
    private handleInstanceInvoke;
    private handleArkAssignStmt;
    private handlePtrInvoke;
    private handleStaticInvoke;
    private handleLocal;
    private checkAncestor;
    private inTry;
    private inCatch;
    private hasFinallyBlock;
    private isReturnPromiseInFinally;
    ruleFix(sourceFile: ts.SourceFile, loc: LocationInfo): RuleFix;
    private removeFirstAwait;
    private reportIssue;
    private getMessageDescription;
}
export {};
