import { ArkFile } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects, IssueReport } from "../../model/Defects";
import { Rule } from "../../model/Rule";
import { MatcherCallback } from "../../Index";
export declare class SemiCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private arkFile;
    private sourceFile;
    private sourceCode;
    private sourceCodeLength;
    private static readonly whitespaceRegex;
    private static readonly commentRegex;
    private static readonly statementContinuationChars;
    private options;
    private fileMatcher;
    private nodeCache;
    private visitedNodes;
    private blockCache;
    private lineCache;
    registerMatchers(): MatcherCallback[];
    check(arkFile: ArkFile): void;
    private preProcessSemiAtLineStart;
    private findNodeAtPosition;
    private getNodeInfo;
    private getLineAndCharacter;
    private getLineStart;
    private visitNode;
    private processDeclarationNodes;
    private processStatementNodes;
    private processClassAndInterfaceNodes;
    private processBlockAndFunctionNodes;
    private processExpressionNodes;
    private handleImportDeclaration;
    private handleTypeAliasDeclaration;
    private handleIfStatementNodes;
    private handleWhileStatementNodes;
    private handleInterfaceAndModuleNodes;
    private handleClassDeclarationNodes;
    private handleBlockNodes;
    private handleVariableStatementNodes;
    private handleExpressionStatementNodes;
    private handleCallExpressionNodes;
    private checkParentNodeContext;
    private checkFunctionArguments;
    private checkFunctionBodyStatements;
    private handleObjectLiteralExpressions;
    private handleClassDeclaration;
    private handlePropertyDeclaration;
    private handleMethodWithBody;
    private handleStaticBlockDeclaration;
    private handleFunctionDeclaration;
    private handleMethodDeclaration;
    private handleClassStaticBlock;
    private handleFunctionExpression;
    private checkExpressionStatementSemicolon;
    private handleVariableDeclarationWithClass;
    private checkVariableDeclaration;
    private isStatement;
    private isBlockInControlFlow;
    private isClassInSpecialContext;
    private isInterfaceOrModuleOrEnum;
    private isControlFlowStatement;
    private isExportedInterface;
    private isFunctionOrMethodWithDeclare;
    private isCommonStatementType;
    private handleIncrementDecrementExpression;
    private handleWhileStatementBlock;
    private handleOneLineBlock;
    private handleSemicolonRule;
    private checkSemicolon;
    private isExpressionInClassStaticBlock;
    private checkStaticBlockExpression;
    private shouldSkipNodeCheck;
    private isControlFlowStatementWithoutSemicolon;
    private isBlockInSpecialContext;
    private processSemicolonForNode;
    private isSameLineNonComment;
    private isLastInOneLineBlock;
    private isLastInOneLineClassBody;
    private getNextCharacter;
    private skipWhitespaceChars;
    private trySkipComment;
    private handleCommentSkip;
    private skipLineComment;
    private skipBlockComment;
    private isStatementContinuationChar;
    private isCommentStart;
    private getNextNonWhitespaceChar;
    private report;
    private isExpressionPartOfVariableDeclaration;
    private checkFunctionCallSemicolon;
    private handleReturnStatement;
    private handleTryStatement;
    private handleBreakContinueStatement;
    private handleThrowStatement;
    private handleDoWhileStatement;
    private handleArrowFunctionExpression;
    private checkCallExpressionSemicolon;
    private deepVisitBlockStatements;
    private processIfStatementBranches;
    private processWhileStatement;
    private processTryStatement;
    private processVariableDeclarations;
    private checkParentContextForLiteral;
    private findExpressionStatementAncestor;
    private findAndCheckAllFunctions;
    private checkFunctionBlockStatements;
    private checkIdentifierFunctionBody;
    private checkFunctionCallArguments;
    private checkFunctionArgumentBlockStatements;
    private isSemiAtLineStart;
    private handleForStatement;
}
