import { ArkFile } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class SwitchExhaustivenessCheck implements BaseChecker {
    metaData: BaseMetaData;
    private defaultOptions;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private traverseAST;
    private analyzeSwitch;
    private isVariableOfNumericLiteralType;
    private checkIsNumericLiteralType;
    private getDiscriminantName;
    private isEnumType;
    private checkTypeIsEnum;
    private getPossibleValues;
    private getDeclarationTypeNodeValues;
    private getTypeReferenceValues;
    private getTypeNodeFromDeclaration;
    private inferTypeFromInitializer;
    private getUnionTypeValues;
    private visitDeclarationList;
    private findDeclaration;
    private findTypeAliasDeclaration;
    private findEnumDeclaration;
    private getEnumValues;
    private getCoveredValues;
    private extractCaseValue;
    private isUnionTypeOrEnum;
    private checkTypeNodeFromDeclaration;
    private hasDefaultCase;
    private validateSwitch;
    private processNoNonUnion;
    private parseInvalidCases;
    private getCurrentOptions;
    private reportIssue;
    private getActualValue;
}
