import { ArkMethod } from 'arkanalyzer/lib';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects, IssueReport } from '../../model/Defects';
import { MatcherCallback } from '../../matcher/Matchers';
import { Rule } from '../../model/Rule';
export declare class TripleSlashReferenceCheck implements BaseChecker {
    readonly metaData: BaseMetaData;
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    private fileMatcher;
    private classMatcher;
    private methodMatcher;
    registerMatchers(): MatcherCallback[];
    check: (method: ArkMethod) => void;
    private optionsCheck1;
    private optionsCheck11;
    private optionsCheck12;
    private optionsCheck13;
    private optionsCheck14;
    private optionsCheck15;
    private optionsCheck16;
    private optionsCheck17;
    private optionsCheck2;
    private optionsCheck21;
    private optionsCheck22;
    private optionsCheck23;
    private optionsCheck24;
    private optionsCheck25;
    private optionsCheck3;
    private optionsCheck31;
    private optionsCheck32;
    private optionsCheck33;
    private optionsCheck34;
    private optionsCheck35;
    private AllCheck;
    private AllCheck1;
    private allTypesAlwaysCheck;
    private allTypesAlwaysCheck1;
    private allPathAlwaysCheck;
    private allPathAlwaysCheck1;
    private allTypesNeverCheck;
    private allTypesNeverCheck1;
    private allLibAlwaysCheck;
    private allLibAlwaysCheck1;
    private allPathNeverCheck;
    private allPathNeverCheck1;
    private allLibNeverCheck;
    private allLibNeverCheck1;
    private allTypeAlwaysAndImportCheck;
    private allTypeAlwaysAndImportCheck1;
    private allImportCheck;
    private allImportCheck1;
    private allLibNeverAndImportCheck;
    private allLibNeverAndImportCheck1;
    private allPathNeverAndImportCheck;
    private allPathNeverAndImportCheck1;
    private ImportCheck;
    private pathNeverAndImportCheck;
    private libNeverAndImportCheck;
    private typeAlwaysAndImportCheck;
    private allCheck;
    private typesAlwaysCheck;
    private typesNeverCheck;
    private libAlwaysCheck;
    private pathNeverCheck;
    private pathAlwaysCheck;
    private libNeverCheck;
    private checkSpecial;
    private checkImportInfo;
    private checkImport;
    private extractCode;
    private tripleSlash;
    private DoubleSlash;
    private normalDirectives;
    private libAlwaysDirectives;
    private typesAlwaysDirectives;
    private pathAlwaysDirectives;
    private pathNeverDirectives;
    private libNeverDirectives;
    private typesNeverDirectives;
    private addIssueReport;
    private getLineAndColumn;
}
