import { ArkFile, ts } from 'arkanalyzer';
import { Rule } from '../../Index';
import { BaseChecker, BaseMetaData } from '../BaseChecker';
import { Defects } from '../../Index';
import { MatcherCallback } from '../../Index';
import { IssueReport } from '../../model/Defects';
export declare class UnboundMethodCheck implements BaseChecker {
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    sourceFile: ts.SourceFile;
    private currentClassName;
    private promiseTemArray;
    private defaultOptions;
    private messageStr;
    private shortMessageStr;
    metaData: BaseMetaData;
    private fileMatcher;
    registerMatchers(): MatcherCallback[];
    check: (targetField: ArkFile) => void;
    private addIssueReport;
    private sortMyInvalidPositions;
    private checkUnboundMethod;
    private collectVariableToClassMapping;
    private collectObjectMethodInfo;
    private processObjectProperties;
    private isMethodLikeProperty;
    private isMethodDeclarationLike;
    private collectClassMethodInfo;
    private processClassMembers;
    private findUnboundMethodReferences;
    private collectDefinedClasses;
    private processNode;
    private processPropertyAccessExpression;
    private isNestedPropertyAccess;
    private isExplicitlyDeclaredAsMethod;
    private isClassStaticMethodAccess;
    private handleStaticMethodAccess;
    private isNewInstanceMethodAccess;
    private handleInstanceMethodAccess;
    private isDirectMethodCall;
    private isStaticMethodAccess;
    private isInExtendsClause;
    private isStaticPropertyInStaticMethod;
    private isStaticMethodCallInStaticMethod;
    private isInObjectLiteralOrDestructuring;
    private isInPrototypeChain;
    private isInComputedPropertyName;
    private checkPropertyAccess;
    private shouldSkipPropertyCheck;
    private isDirectClassStaticAccess;
    private containsOptionalChainOrParenthesized;
    private isPropertyMethodReference;
    private isKnownGlobalMethod;
    private isAssignmentWithMethodDeclaration;
    private checkClassMemberType;
    private isInAssignmentContext;
    private findMethodInClassByName;
    private isMatchingClass;
    private findMethodInClassMembers;
    private isMatchingMethod;
    private isInMethodReferenceContext;
    private checkObjectDestructuring;
    private isValidDestructuringContext;
    private getDestructuringInitializer;
    private getDestructuringContextInfo;
    private checkDestructuredElement;
    private checkMethodInfoForUnbound;
    private checkFunctionExpressionProperty;
    private isExemptCase;
    private reportUnboundMethodError;
    private reportDestructuringError;
    private isInitializerWithFunctionExprProperty;
    private checkThisUsage;
    private checkThisVoidAnnotation;
    private isUnboundContext;
    private isBoundUsage;
    private isNonNullAssertionExpression;
    private isInheritedStaticMethod;
    private findClassDeclarationByName;
    private isClassInheritingPromise;
    private isPromiseDescendant;
    private isStaticArrowFunctionProperty;
    private checkAssignmentExpression;
    private processBindingPattern;
    private processObjectLiteral;
    private getClassNameFromExpression;
    private checkClassHasFunctionProperty;
    private findFunctionPropertyInClass;
    private findNodeInSourceFile;
    private isPropertyAccessToFunctionExpression;
}
