import { ArkFile } from "arkanalyzer/lib";
import { BaseChecker, BaseMetaData } from "../BaseChecker";
import { Defects } from "../../model/Defects";
import { MatcherCallback } from "../../matcher/Matchers";
import { Rule } from "../../model/Rule";
import { IssueReport } from "../../model/Defects";
export declare class UnifiedSignaturesCheck implements BaseChecker {
    rule: Rule;
    defects: Defects[];
    issues: IssueReport[];
    metaData: BaseMetaData;
    private fileMatcher;
    private defaultOption;
    registerMatchers(): MatcherCallback[];
    check: (target: ArkFile) => void;
    private checkBodyForOverloadMethods;
    private visit;
    private processSourceFileNode;
    private checkFunctionGroup;
    private checkMethodPairsForUnification;
    private processNonSourceFileNode;
    private processAccessorMethod;
    private checkAccessorPairUnification;
    private getMemberMethod;
    private getFunctionOrMethodInfo;
    private getGetAccessorInfo;
    private getSetAccessorInfo;
    private extractParameters;
    private getNodeMembers;
    private getModuleDeclarationMembers;
    private getTypeOrClassMembers;
    private getTypeAliasMembers;
    private processMethodOverloads;
    private collectMethodDeclarations;
    private groupMethodsByName;
    private checkOverloadMethodGroups;
    private extractMethodInfos;
    private addIssueReport;
    private canUnifyMethods;
    private checkParameterCountCompatibility;
    private performBasicMethodValidation;
    private checkReturnTypeCompatibility;
    private checkAccessorsReturnTypeCompatibility;
    private checkMethodsWithSameParamCount;
    private checkMethodsWithDifferentParamCount;
    private hasExplicitReturnType;
    private getReturnType;
    private isGenericArrayType;
    private isGenericType;
    private canMergeAsUnionType;
    private areParametersCompatibleForUnion;
    private collectParameterTypeDifferences;
    private hasCrossDependency;
    private checkGenericCompatibility;
    private findParameterDifferences;
    private analyzeDifferencesForUnion;
    private generateUnionMergeDetails;
    private canMergeAsOptionalOrRest;
    private hasSpecialGenericArrayCase;
    private identifyMethodsByParamLength;
    private checkOptionalParameterMerge;
    private haveIdenticalPrefixParameters;
    private checkParameterReorderingMerge;
    private hasSameParametersInDifferentOrder;
}
