/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
fn1   ();
Fg=fn2
 ()
let tuii;
new tuii ();

function fn1   () {
 throw new Error('Function not implemented.');
}


function fn2 (): any {
 throw new Error('Function not implemented.');
}

const c=fn6 ();
const n=Fg ()+tr ();
ty ()
fn2
();
fn3      ();

function fn6(): any {
 throw new Error('Function not implemented.');
}

function Fg
() {
 throw new Error('Function not implemented.');
}

function ty
() {
 throw new Error('Function not implemented.');
}

function tr () {
 throw new Error('Function not implemented.');
}

function fn3
() {
 throw new Error('Function not implemented.');
}
