/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

let foo = bar|0;

let foo1 = bar1 |0;
let foo2 = bar2| 0;
let foo3 = bar3 | 0;
let foo4 = sa| 1;
let foo5 = saa |1;
let foo6 = sab | 1;

a1+b1

a2+ b2

a3 +b3

aa?bb:cc

const aaa={bbb:1};

var {bbbb=0}=barA;

function foo8(a11=0) { }