/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
100

if(0) 700

{107}

f(150), {}

a && b11()

a15, b12()


a() && function nFunctionInExpContext () {f();}

(function anInIIFE () {});

injectGlobal`body{ name: apple; }`

a0?.b1;

one.two?.three.four;

(a?.b).c;

a?.['b1'];

one[2]?.[31][4];

a?.b()?.c;

Map<string, number>;