import { ArrayDefinitionCheck } from '../../checker/performance/ArrayDefinitionCheck';
import { AvoidEmptyCallbackCheck } from '../../checker/performance/AvoidEmptyCallbackCheck';
import { AvoidUpdateAutoStateVarAboutToReuseCheck } from '../../checker/performance/AvoidUpdateAutoStateVarAboutToReuseCheck';
import { ConstantPropertyReferencingInLoopsCheck } from '../../checker/performance/ConstantPropertyReferencingInLoopsCheck';
import { EffectkitBlurCheck } from '../../checker/performance/EffectkitBlurCheck';
import { ForeachArgsCheck } from '../../checker/performance/ForEachArgsCheck';
import { ForeachIndexCheck } from '../../checker/performance/ForeachIndexCheck';
import { LottieAnimationDestoryCheck } from '../../checker/performance/LottieAnimationDestoryCheck';
import { HighFrequencyLogCheck } from '../../checker/performance/HighFrequencyLogCheck';
import { LayoutPropertiesScaleCheck } from '../../checker/performance/LayoutPropertiesScaleCheck';
import { RemoveRedundantStateVarCheck } from '../../checker/performance/RemoveRedundantStateVarCheck';
import { TimezoneInterfaceCheck } from '../../checker/performance/TimezoneInterfaceCheck';
import { TypedArrayCheck } from '../../checker/performance/TypedArrayCheck';
import { UseObjectLinkToReplacePropCheck } from '../../checker/performance/UseObjectLinkToReplacePropCheck';
import { WebCacheModeCheck } from '../../checker/performance/WebCacheModeCheck';
import { SparseArrayCheck } from '../../checker/performance/SparseArrayCheck';
import { WaterFlowUpdateDataCheck } from '../../checker/performance/WaterFlowUpdateDataCheck';
import { UnionTypeArrayCheck } from '../../checker/performance/UnionTypeArrayCheck';
import { OptionalParametersCheck } from '../../checker/performance/OptionalParametersCheck';
import { UseGridLayoutOptionsCheck } from '../../checker/performance/UseGridLayoutOptionsCheck';
import { RemoveUnchangedStateVarCheck } from '../../checker/performance/RemoveUnchangedStateVarCheck';
import { JsCodeCacheByPrecompileCheck } from '../../checker/performance/JsCodeCacheByPrecompileCheck';
import { JsCodeCacheByInterceptionCheck } from '../../checker/performance/JsCodeCacheByInterceptionCheck';
import { ImageInterpolationCheck } from '../../checker/correctness/ImageInterpolationCheck';
import { AudioInterruptCheck } from '../../checker/correctness/AudioInterruptCheck';
import { AudioPauseOrMuteCheck } from '../../checker/correctness/AudioPauseOrMuteCheck';
import { AvsessionButtonsCheck } from '../../checker/correctness/AvsessionButtonsCheck';
import { AvsessionMetadataCheck } from '../../checker/correctness/AvsessionMetadataCheck';
import { ImagePixelFormatCheck } from '../../checker/correctness/ImagePixelFormatCheck';
import { ImageSyncLoadCheck } from '../../checker/performance/ImageSyncLoadCheck';
import { ListInScrollCheck } from '../../checker/performance/ListInScrollCheck';
import { MultipleAssociationsStateVarCheck } from '../../checker/performance/MultipleAssociationsStateVarCheck';
import { NumberInitCheck } from '../../checker/performance/NumberInitCheck';
import { SetCachedCountForLazyforeachCheck } from '../../checker/performance/SetCachedCountForLazyforeachCheck';
import { StartWindowIconCheck } from '../../checker/performance/StartWindowIconCheck';
import { SymbolUsageCheck } from '../../checker/security/SymbolUsageCheck';
import { WebOnActiveCheck } from '../../checker/performance/WebOnActiveCheck';
import { GifHardwareDecodingCheck } from '../../checker/performance/GifHardwareDecodingCheck';
import { ModuleTopLevelCodeCheck } from '../../checker/performance/ModuleTopLevelCodeCheck';
import { NoFloatingPromisesCheck } from '../../checker/ArkTS-eslint/NoFloatingPromisesCheck';
import { InitDeclarationsCheck } from '../../checker/ArkTS-eslint/InitDeclarationsCheck';
import { DefaultParamLastCheck } from '../../checker/ArkTS-eslint/DefaultParamLastCheck';
import { ExplicitFunctionReturnTypeCheck } from '../../checker/ArkTS-eslint/ExplicitFunctionReturnTypeCheck';
import { ExplicitModuleBoundaryTypesCheck } from '../../checker/ArkTS-eslint/ExplicitModuleBoundaryTypesCheck';
import { NoDupeClassMembersCheck } from '../../checker/ArkTS-eslint/NoDupeClassMembersCheck';
import { BanTsCommentCheck } from '../../checker/ArkTS-eslint/BanTsCommentCheck';
import { MemberOrderingCheck } from '../../checker/ArkTS-eslint/MemberOrderingCheck';
import { NoUnnecessaryConditionCheck } from '../../checker/ArkTS-eslint/NoUnnecessaryConditionCheck';
import { NoUnnecessaryQualifierCheck } from '../../checker/ArkTS-eslint/NoUnnecessaryQualifierCheck';
import { NoUnnecessaryTypeArgumentsCheck } from '../../checker/ArkTS-eslint/NoUnnecessaryTypeArgumentsCheck';
import { NoUnnecessaryTypeAssertionCheck } from '../../checker/ArkTS-eslint/NoUnnecessaryTypeAssertionCheck';
import { ValidTypeofCheck } from '../../checker/ArkTS-eslint/ValidTypeofCheck';
import { ArrayTypeCheck } from '../../checker/ArkTS-eslint/ArrayTypeCheck';
import { NoUselessBackreferenceCheck } from '../../checker/ArkTS-eslint/NoUselessBackreferenceCheck';
import { BanTSLintCommentCheck } from '../../checker/ArkTS-eslint/BanTSLintCommentCheck';
import { BanTypesCheck } from '../../checker/ArkTS-eslint/BanTypesCheck';
import { BraceStyleCheck } from '../../checker/ArkTS-eslint/BraceStyleCheck';
import { NoUnsafeOptionalChainingCheck } from '../../checker/ArkTS-eslint/NoUnsafeOptionalChainingCheck';
import { NoUselessEscapeCheck } from '../../checker/ArkTS-eslint/NoUselessEscapeCheck';
import { NoThisAliasCheck } from '../../checker/ArkTS-eslint/NoThisAliasCheck';
import { NoNonNullAssertionCheck } from '../../checker/ArkTS-eslint/NoNonNullAssertionCheck';
import { NoMisusedNewCheck } from '../../checker/ArkTS-eslint/NoMisusedNewCheck';
import { NoRequireImportsCheck } from '../../checker/ArkTS-eslint/NoRequireImportsCheck';
import { NoParameterPropertiesCheck } from '../../checker/ArkTS-eslint/NoParameterPropertiesCheck';
import { NoRedeclareCheck } from '../../checker/ArkTS-eslint/NoRedeclareCheck';
import { NoShadowCheck } from '../../checker/ArkTS-eslint/NoShadowCheck';
import { NoNonNullAssertedOptionalChainCheck } from '../../checker/ArkTS-eslint/NoNonNullAssertedOptionalChainCheck';
import { ConsistentTypeAssertionsCheck } from '../../checker/ArkTS-eslint/ConsistentTypeAssertionsCheck';
import { ConsistentTypeDefinitionsCheck } from '../../checker/ArkTS-eslint/ConsistentTypeDefinitionsCheck';
import { ConsistentTypeImportsCheck } from '../../checker/ArkTS-eslint/ConsistentTypeImportsCheck';
import { ConsistentIndexedObjectStyleCheck } from '../../checker/ArkTS-eslint/ConsistentIndexedObjectStyleCheck';
import { NoUselessCatchCheck } from '../../checker/ArkTS-eslint/NoUselessCatchCheck';
import { NoNewWrappersCheck } from '../../checker/ArkTS-eslint/NoNewWrappersCheck';
import { NoCondAssignCheck } from '../../checker/ArkTS-eslint/NoCondAssignCheck';
import { MaxLinesPerFunctionCheck } from '../../checker/ArkTS-eslint/MaxLinesPerFunctionCheck';
import { NoDuplicateImportsCheck } from '../../checker/ArkTS-eslint/NoDuplicateImportsCheck';
import { NoForInArrayCheck } from '../../checker/ArkTS-eslint/NoForInArrayCheck';
import { NoLoopFuncCheck } from '../../checker/ArkTS-eslint/NoLoopFuncCheck';
import { NoLossOfPrecisionCheck } from '../../checker/ArkTS-eslint/NoLossOfPrecisionCheck';
import { NoExtraneousClassCheck } from '../../checker/ArkTS-eslint/NoExtraneousClassCheck';
import { NoArrayConstructorCheck } from '../../checker/ArkTS-eslint/NoArrayConstructorCheck';
import { NoCaseDeclarationsCheck } from '../../checker/ArkTS-eslint/NoCaseDeclarationsCheck';
import { NoUnsafeAssignmentCheck } from '../../checker/ArkTS-eslint/NoUnsafeAssignmentCheck';
import { MaxLinesCheck } from '../../checker/ArkTS-eslint/MaxLinesCheck';
import { DefaultCaseCheck } from '../../checker/ArkTS-eslint/DefaultCaseCheck';
import { DefaultCaseLastCheck } from '../../checker/ArkTS-eslint/DefaultCaseLastCheck';
import { UseIsNaNCheck } from '../../checker/ArkTS-eslint/UseIsNaNCheck';
import { TypedefCheck } from '../../checker/ArkTS-eslint/TypedefCheck';
import { NoNameSpaceCheck } from '../../checker/ArkTS-eslint/NoNameSpaceCheck';
import { MaxDepthCheck } from '../../checker/ArkTS-eslint/MaxDepthCheck';
import { MaxClassesPerFileCheck } from '../../checker/ArkTS-eslint/MaxClassesPerFileCheck';
import { MaxNestedCallbacksCheck } from '../../checker/ArkTS-eslint/MaxNestedCallbacksCheck';
import { NoAsyncPromiseExecutorCheck } from '../../checker/ArkTS-eslint/NoAsyncPromiseExecutorCheck';
import { NoUnsafeCallCheck } from '../../checker/ArkTS-eslint/NoUnsafeCallCheck';
import { NoUnnecessaryTypeConstraintCheck } from '../../checker/ArkTS-eslint/NoUnnecessaryTypeConstraintCheck';
import { NoUnsafeArgumentCheck } from '../../checker/ArkTS-eslint/NoUnsafeArgumentCheck';
import { NoControlRegexCheck } from '../../checker/ArkTS-eslint/NoControlRegexCheck';
import { NoEmptyCharacterClassCheck } from '../../checker/ArkTS-eslint/NoEmptyCharacterClassCheck';
import { NoInvalidRegexpCheck } from '../../checker/ArkTS-eslint/NoInvalidRegexpCheck';
import { NoExAssignCheck } from '../../checker/ArkTS-eslint/NoExAssignCheck';
import { NoOctalCheck } from '../../checker/ArkTS-eslint/NoOctalCheck';
import { RequireAwaitCheck } from '../../checker/ArkTS-eslint/RequireAwaitCheck';
import { SwitchExhaustivenessCheck } from '../../checker/ArkTS-eslint/SwitchExhaustivenessCheck';
import { UnifiedSignaturesCheck } from '../../checker/ArkTS-eslint/UnifiedSignaturesCheck';
import { NoUnexpectedMultilineCheck } from '../../checker/ArkTS-eslint/NoUnexpectedMultilineCheck';
import { NoUnreachableCheck } from '../../checker/ArkTS-eslint/NoUnreachableCheck';
import { NoInferrableTypesCheck } from '../../checker/ArkTS-eslint/NoInferrableTypesCheck';
import { SpaceInfixOpsCheck } from '../../checker/ArkTS-eslint/SpaceInfixOpsCheck';
import { SpaceBeforeFunctionParenCheck } from '../../checker/ArkTS-eslint/SpaceBeforeFunctionParenCheck';
import { NoRestrictedSyntaxCheck } from '../../checker/ArkTS-eslint/NoRestrictedSyntaxCheck';
import { AdjacentOverloadSignaturesCheck } from '../../checker/ArkTS-eslint/AdjacentOverloadSignaturesCheck';
import { ClassLiteralPropertyStyleCheck } from '../../checker/ArkTS-eslint/ClassLiteralPropertyStyleCheck';
import { NoEmptyFunctionCheck } from '../../checker/ArkTS-eslint/NoEmptyFunctionCheck';
import { PreferForOfCheck } from '../../checker/ArkTS-eslint/PreferForOfCheck';
import { NoConfusingNonNullAssertionCheck } from '../../checker/ArkTS-eslint/NoConfusingNonNullAssertionCheck';
import { NoMagicNumbersCheck } from '../../checker/ArkTS-eslint/NoMagicNumbersCheck';
import { AwaitThenableCheck } from '../../checker/ArkTS-eslint/AwaitThenableCheck';
import { NoUselessConstructorCheck } from '../../checker/ArkTS-eslint/NoUselessConstructorCheck';
import { PreferEnumInitializwersCheck } from '../../checker/ArkTS-eslint/PreferEnumInitializwersCheck';
import { PreferLiteralEnumMemberCheck } from '../../checker/ArkTS-eslint/PreferLiteralEnumMemberCheck';
import { PreferReadonlyParametertypesCheck } from '../../checker/ArkTS-eslint/PreferReadonlyParametertypesCheck';
import { RequireArraySortCompareCheck } from '../../checker/ArkTS-eslint/RequireArraySortCompareCheck';
import { NoUnusedVarsCheck } from '../../checker/ArkTS-eslint/NoUnusedVarsCheck';
import { NoInvalidVoidTypeCheck } from '../../checker/ArkTS-eslint/NoInvalidVoidTypeCheck';
import { NoInvalidThisCheck } from '../../checker/ArkTS-eslint/NoInvalidThisCheck';
import { NoFallthroughCheck } from '../../checker/ArkTS-eslint/NoFallthroughCheck';
import { NoBaseToStringCheck } from '../../checker/ArkTS-eslint/NoBaseToStringCheck';
import { NoExplicitAnyCheck } from '../../checker/ArkTS-eslint/NoExplicitAnyCheck';
import { NamingConventionCheck } from '../../checker/ArkTS-eslint/NamingConventionCheck';
import { NoUnusedExpressionsCheck } from '../../checker/ArkTS-eslint/NoUnusedExpressionsCheck';
import { NoUnsafeMemberAccessCheck } from '../../checker/ArkTS-eslint/NoUnsafeMemberAccessCheck';
import { NoThrowLiteralCheck } from '../../checker/ArkTS-eslint/NoThrowLiteralCheck';
import { EqeqeqCheck } from '../../checker/ArkTS-eslint/EqeqeqCheck';
import { NoExtraSemiCheck } from '../../checker/ArkTS-eslint/NoExtraSemiCheck';
import { CommaDangleCheck } from '../../checker/ArkTS-eslint/CommaDangleCheck';
import { PreferRegexpExecCheck } from '../../checker/ArkTS-eslint/PreferRegexpExecCheck';
import { PreferTsExpectErrorCheck } from '../../checker/ArkTS-eslint/PreferTsExpectErrorCheck';
import { DotNotationCheck } from '../../checker/ArkTS-eslint/DotNotationCheck';
import { ExplicitMemberAccessibilityCheck } from '../../checker/ArkTS-eslint/ExplicitMemberAccessibilityCheck';
import { NoExtraParensCheck } from '../../checker/ArkTS-eslint/NoExtraParensCheck';
import { NoDynamicDeleteCheck } from '../../checker/ArkTS-eslint/NoDynamicDeleteCheck';
import { NoImplicitAnyCatchCheck } from '../../checker/ArkTS-eslint/NoImplicitAnyCatchCheck';
import { NoEmptyInterfaceCheck } from '../../checker/ArkTS-eslint/NoEmptyInterfaceCheck';
import { NoUnsafeFinallyCheck } from '../../checker/ArkTS-eslint/NoUnsafeFinallyCheck';
import { PreferFunctionTypeCheck } from '../../checker/ArkTS-eslint/PreferFunctionTypeCheck';
import { PreferNamespaceKeywordCheck } from '../../checker/ArkTS-eslint/PreferNamespaceKeywordCheck';
import { PreferNullishCoalescingCheck } from '../../checker/ArkTS-eslint/PreferNullishCoalescingCheck';
import { ReturnAwaitCheck } from '../../checker/ArkTS-eslint/ReturnAwaitCheck';
import { PreferReduceTypeParameterCheck } from '../../checker/ArkTS-eslint/PreferReduceTypeParameterCheck';
import { CommaSpacingCheck } from '../../checker/ArkTS-eslint/CommaSpacingCheck';
import { NoExtraNonNullAssertionCheck } from '../../checker/ArkTS-eslint/NoExtraNonNullAssertionCheck';
import { NoTypeAliasCheck } from '../../checker/ArkTS-eslint/NoTypeAliasCheck';
import { NoMisusedPromisesCheck } from '../../checker/ArkTS-eslint/NoMisusedPromisesCheck';
import { TypeAnnotationSpacingCheck } from '../../checker/ArkTS-eslint/TypeAnnotationSpacingCheck';
import { StrictBooleanExpressionsCheck } from '../../checker/ArkTS-eslint/StrictBooleanExpressionsCheck';
import { SemiCheck } from '../../checker/ArkTS-eslint/SemiCheck';
import { NoArrayConstructorTSCheck } from '../../checker/ArkTS-eslint/NoArrayConstructorTSCheck';
import { PreferStringStartsEndsWithCheck } from '../../checker/ArkTS-eslint/PreferStringStartsEndsWithCheck';
import { PromiseFunctionAsyncCheck } from '../../checker/ArkTS-eslint/PromiseFunctionAsyncCheck';
import { KeywordSpacingCheck } from '../../checker/ArkTS-eslint/KeywordSpacingCheck';
import { FuncCallSpacingCheck } from '../../checker/ArkTS-eslint/FuncCallSpacingCheck';
import { MethodSignatureStyleCheck } from '../../checker/ArkTS-eslint/MethodSignatureStyleCheck';
import { LinesBetweenClassMembersCheck } from '../../checker/ArkTS-eslint/LinesBetweenClassMembersCheck';
import { MemberDelimiterStyleCheck } from '../../checker/ArkTS-eslint/MemberDelimiterStyleCheck';
import { NoUnsafeReturnCheck } from '../../checker/ArkTS-eslint/NoUnsafeReturnCheck';
import { PreferReadonlyCheck } from '../../checker/ArkTS-eslint/PreferReadonlyCheck';
import { NoUseBeforeDefineCheck } from '../../checker/ArkTS-eslint/NoUseBeforeDefineCheck';
import { PreferAsConstCheck } from '../../checker/ArkTS-eslint/PreferAsConstCheck';
import { QuotesCheck } from '../../checker/ArkTS-eslint/QuotesCheck';
import { NoRegexSpacesCheck } from '../../checker/ArkTS-eslint/NoRegexSpacesCheck';
import { PreferOptionalChainCheck } from '../../checker/ArkTS-eslint/PreferOptionalChainCheck';
import { NoTrailingSpacesCheck } from '../../checker/ArkTS-eslint/NoTrailingSpacesCheck';
import { NoExtraBooleanCastCheck } from '../../checker/ArkTS-eslint/NoExtraBooleanCastCheck';
import { NoConfusingVoidExpressionCheck } from '../../checker/ArkTS-eslint/NoConfusingVoidExpressionCheck';
import { PreferArrowCallbackCheck } from '../../checker/ArkTS-eslint/PreferArrowCallbackCheck';
import { NoUnnecessaryBooleanLiteralCompareCheck } from '../../checker/ArkTS-eslint/NoUnnecessaryBooleanLiteralCompareCheck';
import { NoImpliedEvalCheck } from '../../checker/ArkTS-eslint/NoImpliedEvalCheck';
import { PreferConstCheck } from '../../checker/ArkTS-eslint/PreferConstCheck';
import { PreferIncludesCheck } from '../../checker/ArkTS-eslint/PreferIncludesCheck';
import { RestrictPlusOperandsCheck } from '../../checker/ArkTS-eslint/RestrictPlusOperandsCheck';
import { UnboundMethodCheck } from '../../checker/ArkTS-eslint/UnboundMethodCheck';
import { RestrictTemplateExpressionsCheck } from '../../checker/ArkTS-eslint/RestrictTemplateExpressionsCheck';
import { TripleSlashReferenceCheck } from '../../checker/ArkTS-eslint/TripleSlashReferenceCheck';
import { CacheAvplayerCheck } from '../../checker/performance/CacheAvplayerCheck';
import { ColorOverlayEffectCheck } from '../../checker/performance/ColorOverlayEffectCheck';
import { CombineSameArgAnimatetoCheck } from '../../checker/performance/CombineSameArgAnimatetoCheck';
import { ConstantCheck } from '../../checker/performance/ConstantCheck';
import { HomepagePrepareLoadCheck } from '../../checker/performance/HomepagePrepareLoadCheck';
import { ImageFormatCheck } from '../../checker/performance/ImageFormatCheck';
import { ImageSizeCheck } from '../../checker/performance/ImageSizeCheck';
import { LimitRefreshScopeCheck } from '../../checker/performance/LimitRefreshScopeCheck';
import { LoadOnDemandCheck } from '../../checker/performance/LoadOnDemandCheck';
import { NoStateVarAccessInLoopCheck } from '../../checker/performance/NoStateVarAccessInLoopCheck';
import { NoUseAnyExportCurrentCheck } from '../../checker/performance/NoUseAnyExportCurrentCheck';
import { NoUseAnyExportOtherCheck } from '../../checker/performance/NoUseAnyExportOtherCheck';
import { PagePrefetchCheck } from '../../checker/performance/PagePrefetchCheck';
import { RemoveContainerWithoutPropertyCheck } from '../../checker/performance/RemoveContainerWithoutPropertyCheck';
import { ReplaceNestedReusableComponentByBuilderCheck } from '../../checker/performance/ReplaceNestedReusableComponentByBuilderCheck';
import { ResourcesFileCheck } from '../../checker/performance/ResourcesFileCheck';
import { SuggestReuseidForIfElseReusableComponentCheck } from '../../checker/performance/SuggestReuseidForlfElseReusableComponentCheck';
import { UseAttributeUpdaterControlRefreshScopeCheck } from '../../checker/performance/UseAttributeUpdaterControlRefreshScopeCheck';
import { UseReusableComponentCheck } from '../../checker/performance/UseReusableComponentCheck';
import { WebResourceForImageComponentCheck } from '../../checker/performance/WebResourceForImageComponentCheck';
import { NoCycleCheck } from '../../checker/security/NoCycleCheck';
import { NoUnsafeAesCheck } from '../../checker/security/NoUnsafeAesCheck';
import { NoUnsafeDhCheck } from '../../checker/security/NoUnsafeDhCheck';
import { NoUnsafeDhKeyCheck } from '../../checker/security/NoUnsafeDhKeyCheck';
import { NoUnsafeDsaCheck } from '../../checker/security/NoUnsafeDsaCheck';
import { NoUnsafeDsaKeyCheck } from '../../checker/security/NoUnsafeDsaKeyCheck';
import { NoUnsafeEcdsaCheck } from '../../checker/security/NoUnsafeEcdsaCheck';
import { NoUnsafeHashCheck } from '../../checker/security/NoUnsafeHashCheck';
import { NoUnsafeRsaEncryptCheck } from '../../checker/security/NoUnsafeRsaEncryptCheck';
import { NoUnsafeRsaKeyCheck } from '../../checker/security/NoUnsafeRsaKeyCheck';
import { NoUnsafeMacCheck } from '../../checker/security/NoUnsafeMacCheck';
import { NoUnsafeRsaSignCheck } from '../../checker/security/NoUnsafeRsaSignCheck';
import { NoHighLoadedFrameRateRangeCheck } from '../../checker/performance/NoHighLoadedFrameRateRangeCheck';
import { OneMultiBreakpointCheck } from '../../checker/cross-device-app-dev/OneMultiBreakpointCheck';
import { AvoidInspectorInterfaceCheck } from '../../checker/stability/AvoidInspectorInterfaceCheck';
import { AwaitTimeSequenceNormalCheck } from '../../checker/stability/AwaitTimeSequenceNormalCheck';
import { BanCallbackOperationsCheck } from '../../checker/stability/BanCallbackOperationsCheck';
import { CallAddInputBeforeAddOutputCheck } from '../../checker/stability/CallAddInputBeforeAddOutputCheck';
import { CameraInputOpenCheck } from '../../checker/stability/CameraInputOpenCheck';
import { ImageSyncBlurCheck } from '../../checker/stability/ImageSyncBlurCheck';
import { DarkColorModeCheck } from '../../checker/performance/DarkColorModeCheck';
import { LowerAppBrightnessCheck } from '../../checker/performance/LowerAppBrightnessCheck';
import { StreamUsageApiCheck } from '../../checker/performance/StreamUsageApiCheck';
import { AvoidMemoryLeakInAnimator } from '../../checker/performance/AvoidMemoryLeakInAnimator';
import { AvoidMemoryLeakInDisplaysync } from '../../checker/performance/AvoidMemoryLeakInDisplaysync';
import { CommandExecutionCheck } from '../../checker/SoftwareSecurity26/Checker19241042/CommandExecutionCheck';
import { CommandExecutionCheck as CommandExecutionCheck23373456 } from '../../checker/SoftwareSecurity26/Checker23373456/CommandExecutionCheck';
import { HardcodedSecretCheck } from '../../checker/SoftwareSecurity26/Checker23373456/HardcodedSecretCheck';
import { SQLInjectionCheck } from '../../checker/SoftwareSecurity26/Checker23373456/SQLInjectionCheck';
import { PathTraversalCheck } from '../../checker/SoftwareSecurity26/Checker23373456/PathTraversalCheck';
export declare const fileRules: {
    "@ArkTS-eslint/init-declarations-check": typeof InitDeclarationsCheck;
    "@ArkTS-eslint/default-param-last-check": typeof DefaultParamLastCheck;
    "@ArkTS-eslint/explicit-function-return-type-check": typeof ExplicitFunctionReturnTypeCheck;
    "@ArkTS-eslint/explicit-module-boundary-types-check": typeof ExplicitModuleBoundaryTypesCheck;
    "@ArkTS-eslint/no-dupe-class-members-check": typeof NoDupeClassMembersCheck;
    "@ArkTS-eslint/ban-ts-comment-check": typeof BanTsCommentCheck;
    "@ArkTS-eslint/member-ordering-check": typeof MemberOrderingCheck;
    "@ArkTS-eslint/no-unsafe-optional-chaining-check": typeof NoUnsafeOptionalChainingCheck;
    "@ArkTS-eslint/no-unnecessary-condition-check": typeof NoUnnecessaryConditionCheck;
    "@ArkTS-eslint/no-unnecessary-qualifier-check": typeof NoUnnecessaryQualifierCheck;
    "@ArkTS-eslint/no-unnecessary-type-arguments-check": typeof NoUnnecessaryTypeArgumentsCheck;
    "@ArkTS-eslint/no-unnecessary-type-assertion-check": typeof NoUnnecessaryTypeAssertionCheck;
    "@ArkTS-eslint/require-await-check": typeof RequireAwaitCheck;
    "@ArkTS-eslint/prefer-arrow-callback-check": typeof PreferArrowCallbackCheck;
    "@ArkTS-eslint/no-unnecessary-boolean-literal-compare-check": typeof NoUnnecessaryBooleanLiteralCompareCheck;
    "@ArkTS-eslint/switch-exhaustiveness-check": typeof SwitchExhaustivenessCheck;
    "@ArkTS-eslint/unified-signatures-check": typeof UnifiedSignaturesCheck;
    "@ArkTS-eslint/restrict-plus-operands-check": typeof RestrictPlusOperandsCheck;
    "@ArkTS-eslint/restrict-template-expressions-check": typeof RestrictTemplateExpressionsCheck;
    "@ArkTS-eslint/unbound-method-check": typeof UnboundMethodCheck;
    "@ArkTS-eslint/triple-slash-reference-check": typeof TripleSlashReferenceCheck;
    "@ArkTS-eslint/valid-typeof-check": typeof ValidTypeofCheck;
    "@ArkTS-eslint/array-type-check": typeof ArrayTypeCheck;
    "@ArkTS-eslint/no-floating-promises-check": typeof NoFloatingPromisesCheck;
    "@ArkTS-eslint/no-useless-backreference-check": typeof NoUselessBackreferenceCheck;
    "@ArkTS-eslint/ban-tslint-comment-check": typeof BanTSLintCommentCheck;
    "@ArkTS-eslint/ban-types-check": typeof BanTypesCheck;
    "@ArkTS-eslint/brace-style-check": typeof BraceStyleCheck;
    "@ArkTS-eslint/no-useless-escape-check": typeof NoUselessEscapeCheck;
    "@ArkTS-eslint/no-this-alias-check": typeof NoThisAliasCheck;
    "@ArkTS-eslint/no-non-null-assertion-check": typeof NoNonNullAssertionCheck;
    "@ArkTS-eslint/no-misused-new-check": typeof NoMisusedNewCheck;
    "@ArkTS-eslint/no-require-imports-check": typeof NoRequireImportsCheck;
    "@ArkTS-eslint/no-parameter-properties-check": typeof NoParameterPropertiesCheck;
    "@ArkTS-eslint/no-redeclare-check": typeof NoRedeclareCheck;
    "@ArkTS-eslint/no-shadow-check": typeof NoShadowCheck;
    "@ArkTS-eslint/no-non-null-asserted-optional-chain-check": typeof NoNonNullAssertedOptionalChainCheck;
    "@ArkTS-eslint/consistent-type-assertions-check": typeof ConsistentTypeAssertionsCheck;
    "@ArkTS-eslint/consistent-type-definitions-check": typeof ConsistentTypeDefinitionsCheck;
    "@ArkTS-eslint/consistent-type-imports-check": typeof ConsistentTypeImportsCheck;
    "@ArkTS-eslint/consistent-indexed-object-style-check": typeof ConsistentIndexedObjectStyleCheck;
    "@ArkTS-eslint/no-useless-catch-check": typeof NoUselessCatchCheck;
    "@ArkTS-eslint/no-new-wrappers-check": typeof NoNewWrappersCheck;
    "@ArkTS-eslint/no-cond-assign-check": typeof NoCondAssignCheck;
    "@ArkTS-eslint/max-lines-per-function-check": typeof MaxLinesPerFunctionCheck;
    "@ArkTS-eslint/no-duplicate-imports-check": typeof NoDuplicateImportsCheck;
    "@ArkTS-eslint/no-regex-spaces-check": typeof NoRegexSpacesCheck;
    "@ArkTS-eslint/no-loop-func-check": typeof NoLoopFuncCheck;
    "@ArkTS-eslint/no-extraneous-class-check": typeof NoExtraneousClassCheck;
    "@ArkTS-eslint/no-loss-of-precision-check": typeof NoLossOfPrecisionCheck;
    "@ArkTS-eslint/no-for-in-array-check": typeof NoForInArrayCheck;
    "@ArkTS-eslint/max-classes-per-file-check": typeof MaxClassesPerFileCheck;
    "@ArkTS-eslint/max-nested-callbacks-check": typeof MaxNestedCallbacksCheck;
    "@ArkTS-eslint/no-async-promise-executor-check": typeof NoAsyncPromiseExecutorCheck;
    "@ArkTS-eslint/no-array-constructor-check": typeof NoArrayConstructorCheck;
    "@ArkTS-eslint/max-depth-check": typeof MaxDepthCheck;
    "@ArkTS-eslint/eqeqeq-check": typeof EqeqeqCheck;
    "@ArkTS-eslint/no-extra-semi-check": typeof NoExtraSemiCheck;
    "@ArkTS-eslint/no-array-constructor-ts-check": typeof NoArrayConstructorTSCheck;
    "@ArkTS-eslint/no-extra-boolean-cast-check": typeof NoExtraBooleanCastCheck;
    "@ArkTS-eslint/no-confusing-void-expression-check": typeof NoConfusingVoidExpressionCheck;
    "@ArkTS-eslint/prefer-const-check": typeof PreferConstCheck;
    "@ArkTS-eslint/no-case-declarations-check": typeof NoCaseDeclarationsCheck;
    "@ArkTS-eslint/no-unsafe-assignment-check": typeof NoUnsafeAssignmentCheck;
    "@ArkTS-eslint/max-lines-check": typeof MaxLinesCheck;
    "@ArkTS-eslint/default-case-check": typeof DefaultCaseCheck;
    "@ArkTS-eslint/default-case-last-check": typeof DefaultCaseLastCheck;
    "@ArkTS-eslint/use-isnan-check": typeof UseIsNaNCheck;
    "@ArkTS-eslint/no-invalid-void-type-check": typeof NoInvalidVoidTypeCheck;
    "@ArkTS-eslint/no-namespace-check": typeof NoNameSpaceCheck;
    "@ArkTS-eslint/typedef-check": typeof TypedefCheck;
    "@ArkTS-eslint/no-unnecessary-type-constraint-check": typeof NoUnnecessaryTypeConstraintCheck;
    "@ArkTS-eslint/no-unsafe-argument-check": typeof NoUnsafeArgumentCheck;
    "@ArkTS-eslint/no-unsafe-call-check": typeof NoUnsafeCallCheck;
    "@ArkTS-eslint/no-control-regex-check": typeof NoControlRegexCheck;
    "@ArkTS-eslint/no-empty-character-class-check": typeof NoEmptyCharacterClassCheck;
    "@ArkTS-eslint/no-invalid-regexp-check": typeof NoInvalidRegexpCheck;
    "@ArkTS-eslint/no-ex-assign-check": typeof NoExAssignCheck;
    "@ArkTS-eslint/no-octal-check": typeof NoOctalCheck;
    "@ArkTS-eslint/no-unexpected-multiline-check": typeof NoUnexpectedMultilineCheck;
    "@ArkTS-eslint/no-unreachable-check": typeof NoUnreachableCheck;
    "@ArkTS-eslint/no-inferrable-types-check": typeof NoInferrableTypesCheck;
    "@ArkTS-eslint/space-infix-ops-check": typeof SpaceInfixOpsCheck;
    "@ArkTS-eslint/space-before-function-paren-check": typeof SpaceBeforeFunctionParenCheck;
    "@ArkTS-eslint/no-restricted-syntax-check": typeof NoRestrictedSyntaxCheck;
    "@ArkTS-eslint/adjacent-overload-signatures-check": typeof AdjacentOverloadSignaturesCheck;
    "@ArkTS-eslint/class-literal-property-style-check": typeof ClassLiteralPropertyStyleCheck;
    "@ArkTS-eslint/no-confusing-non-null-assertion-check": typeof NoConfusingNonNullAssertionCheck;
    "@ArkTS-eslint/no-empty-function-check": typeof NoEmptyFunctionCheck;
    "@ArkTS-eslint/prefer-for-of-check": typeof PreferForOfCheck;
    "@ArkTS-eslint/no-magic-numbers-check": typeof NoMagicNumbersCheck;
    "@ArkTS-eslint/return-await-check": typeof ReturnAwaitCheck;
    "@ArkTS-eslint/prefer-reduce-type-parameter-check": typeof PreferReduceTypeParameterCheck;
    "@ArkTS-eslint/prefer-nullish-coalescing-check": typeof PreferNullishCoalescingCheck;
    "@ArkTS-eslint/await-thenable-check": typeof AwaitThenableCheck;
    "@ArkTS-eslint/no-useless-constructor-check": typeof NoUselessConstructorCheck;
    "@ArkTS-eslint/prefer-enum-initializers-check": typeof PreferEnumInitializwersCheck;
    "@ArkTS-eslint/prefer-literal-enum-member-check": typeof PreferLiteralEnumMemberCheck;
    "@ArkTS-eslint/prefer-readonly-parameter-types-check": typeof PreferReadonlyParametertypesCheck;
    "@ArkTS-eslint/require-array-sort-compare-check": typeof RequireArraySortCompareCheck;
    "@ArkTS-eslint/no-unused-vars-check": typeof NoUnusedVarsCheck;
    "@ArkTS-eslint/no-invalid-this-check": typeof NoInvalidThisCheck;
    "@ArkTS-eslint/no-fallthrough-check": typeof NoFallthroughCheck;
    "@ArkTS-eslint/no-base-to-string-check": typeof NoBaseToStringCheck;
    "@ArkTS-eslint/no-explicit-any-check": typeof NoExplicitAnyCheck;
    "@ArkTS-eslint/naming-convention-check": typeof NamingConventionCheck;
    "@ArkTS-eslint/no-unused-expressions-check": typeof NoUnusedExpressionsCheck;
    "@ArkTS-eslint/no-unsafe-member-access-check": typeof NoUnsafeMemberAccessCheck;
    "@ArkTS-eslint/no-throw-literal-check": typeof NoThrowLiteralCheck;
    "@ArkTS-eslint/comma-dangle-check": typeof CommaDangleCheck;
    "@ArkTS-eslint/prefer-regexp-exec-check": typeof PreferRegexpExecCheck;
    "@ArkTS-eslint/prefer-ts-expect-error-check": typeof PreferTsExpectErrorCheck;
    "@ArkTS-eslint/dot-notation-check": typeof DotNotationCheck;
    "@ArkTS-eslint/explicit-member-accessibility-check": typeof ExplicitMemberAccessibilityCheck;
    "@ArkTS-eslint/no-extra-parens-check": typeof NoExtraParensCheck;
    "@ArkTS-eslint/no-dynamic-delete-check": typeof NoDynamicDeleteCheck;
    "@ArkTS-eslint/no-implicit-any-catch-check": typeof NoImplicitAnyCatchCheck;
    "@ArkTS-eslint/no-empty-interface-check": typeof NoEmptyInterfaceCheck;
    "@ArkTS-eslint/no-unsafe-finally-check": typeof NoUnsafeFinallyCheck;
    "@ArkTS-eslint/prefer-function-type-check": typeof PreferFunctionTypeCheck;
    "@ArkTS-eslint/prefer-namespace-keyword-check": typeof PreferNamespaceKeywordCheck;
    "@ArkTS-eslint/comma-spacing-check": typeof CommaSpacingCheck;
    "@ArkTS-eslint/no-extra-non-null-assertion-check": typeof NoExtraNonNullAssertionCheck;
    "@ArkTS-eslint/no-type-alias-check": typeof NoTypeAliasCheck;
    "@ArkTS-eslint/no-misused-promises-check": typeof NoMisusedPromisesCheck;
    "@ArkTS-eslint/type-annotation-spacing-check": typeof TypeAnnotationSpacingCheck;
    "@ArkTS-eslint/strict-boolean-expressions-check": typeof StrictBooleanExpressionsCheck;
    "@ArkTS-eslint/semi-check": typeof SemiCheck;
    "@ArkTS-eslint/prefer-string-starts-ends-with-check": typeof PreferStringStartsEndsWithCheck;
    "@ArkTS-eslint/promise-function-async-check": typeof PromiseFunctionAsyncCheck;
    "@ArkTS-eslint/keyword-spacing-check": typeof KeywordSpacingCheck;
    "@ArkTS-eslint/func-call-spacing-check": typeof FuncCallSpacingCheck;
    "@ArkTS-eslint/method-signature-style-check": typeof MethodSignatureStyleCheck;
    "@ArkTS-eslint/prefer-as-const-check": typeof PreferAsConstCheck;
    "@ArkTS-eslint/lines-between-class-members-check": typeof LinesBetweenClassMembersCheck;
    "@ArkTS-eslint/member-delimiter-style-check": typeof MemberDelimiterStyleCheck;
    "@ArkTS-eslint/no-unsafe-return-check": typeof NoUnsafeReturnCheck;
    "@ArkTS-eslint/no-use-before-define-check": typeof NoUseBeforeDefineCheck;
    "@ArkTS-eslint/prefer-readonly-check": typeof PreferReadonlyCheck;
    "@ArkTS-eslint/quotes-check": typeof QuotesCheck;
    "@ArkTS-eslint/prefer-optional-chain-check": typeof PreferOptionalChainCheck;
    "@ArkTS-eslint/no-trailing-spaces-check": typeof NoTrailingSpacesCheck;
    "@ArkTS-eslint/no-implied-eval-check": typeof NoImpliedEvalCheck;
    "@ArkTS-eslint/prefer-includes-check": typeof PreferIncludesCheck;
    "@performance/array-definition-check": typeof ArrayDefinitionCheck;
    "@performance/avoid-empty-callback-check": typeof AvoidEmptyCallbackCheck;
    "@performance/avoid-update-auto-state-var-in-aboutToReuse-check": typeof AvoidUpdateAutoStateVarAboutToReuseCheck;
    "@performance/constant-property-referencing-check-in-loops": typeof ConstantPropertyReferencingInLoopsCheck;
    "@performance/effectkit-blur-check": typeof EffectkitBlurCheck;
    "@performance/foreach-args-check": typeof ForeachArgsCheck;
    "@performance/foreach-index-check": typeof ForeachIndexCheck;
    "@performance/layout-properties-scale-check": typeof LayoutPropertiesScaleCheck;
    "@performance/remove-redundant-state-var-check": typeof RemoveRedundantStateVarCheck;
    "@performance/timezone-interface-check": typeof TimezoneInterfaceCheck;
    "@performance/typed-array-check": typeof TypedArrayCheck;
    "@performance/use-object-link-to-replace-prop-check": typeof UseObjectLinkToReplacePropCheck;
    "@performance/web-cache-mode-check": typeof WebCacheModeCheck;
    "@performance/web-on-active-check": typeof WebOnActiveCheck;
    "@performance/sparse-array-check": typeof SparseArrayCheck;
    "@performance/waterflow-data-preload-check": typeof WaterFlowUpdateDataCheck;
    "@performance/union-type-array-check": typeof UnionTypeArrayCheck;
    "@performance/optional-parameters-check": typeof OptionalParametersCheck;
    "@performance/use-grid-layout-options-check": typeof UseGridLayoutOptionsCheck;
    "@performance/remove-unchanged-state-var-check": typeof RemoveUnchangedStateVarCheck;
    "@performance/js-code-cache-by-precompile-check": typeof JsCodeCacheByPrecompileCheck;
    "@performance/js-code-cache-by-interception-check": typeof JsCodeCacheByInterceptionCheck;
    "@correctness/image-interpolation-check": typeof ImageInterpolationCheck;
    "@correctness/image-pixel-format-check": typeof ImagePixelFormatCheck;
    "@performance/gif-hardware-decoding-check": typeof GifHardwareDecodingCheck;
    "@performance/cache-avplayer-check": typeof CacheAvplayerCheck;
    "@performance/color-overlay-effect-check": typeof ColorOverlayEffectCheck;
    "@performance/combine-same-arg-animateto-check": typeof CombineSameArgAnimatetoCheck;
    "@performance/constant-check": typeof ConstantCheck;
    "@performance/limit-refresh-scope-check": typeof LimitRefreshScopeCheck;
    "@performance/load-on-demand-check": typeof LoadOnDemandCheck;
    "@performance/no-state-var-access-in-loop-check": typeof NoStateVarAccessInLoopCheck;
    "@performance/no-use-any-export-current-check": typeof NoUseAnyExportCurrentCheck;
    "@performance/no-use-any-export-other-check": typeof NoUseAnyExportOtherCheck;
    "@performance/remove-container-without-property-check": typeof RemoveContainerWithoutPropertyCheck;
    "@performance/replace-nested-reusable-component-by-builder-check": typeof ReplaceNestedReusableComponentByBuilderCheck;
    "@performance/suggest-reuseid-for-if-else-reusable-component-check": typeof SuggestReuseidForIfElseReusableComponentCheck;
    "@performance/use-attribute-updater-control-refresh-scope-check": typeof UseAttributeUpdaterControlRefreshScopeCheck;
    "@performance/use-reusable-component-check": typeof UseReusableComponentCheck;
    "@performance/web-resource-for-image-component-check": typeof WebResourceForImageComponentCheck;
    "@performance/module-top-level-code-check": typeof ModuleTopLevelCodeCheck;
    "@performance/no-high-loaded-frame-rate-range": typeof NoHighLoadedFrameRateRangeCheck;
    "@performance/lower-app-brightness-check": typeof LowerAppBrightnessCheck;
    "@performance/stream-usage-api-check": typeof StreamUsageApiCheck;
    "@performance/avoid-memory-leak-in-animator": typeof AvoidMemoryLeakInAnimator;
    "@performance/avoid-memory-leak-in-displaysync": typeof AvoidMemoryLeakInDisplaysync;
    "@security/no-unsafe-aes-check": typeof NoUnsafeAesCheck;
    "@security/no-unsafe-dh-check": typeof NoUnsafeDhCheck;
    "@security/no-unsafe-dh-key-check": typeof NoUnsafeDhKeyCheck;
    "@security/no-unsafe-dsa-check": typeof NoUnsafeDsaCheck;
    "@security/no-unsafe-dsa-key-check": typeof NoUnsafeDsaKeyCheck;
    "@security/no-unsafe-ecdsa-check": typeof NoUnsafeEcdsaCheck;
    "@security/no-unsafe-hash-check": typeof NoUnsafeHashCheck;
    "@security/no-unsafe-mac-check": typeof NoUnsafeMacCheck;
    "@security/no-unsafe-rsa-encrypt-check": typeof NoUnsafeRsaEncryptCheck;
    "@security/no-unsafe-rsa-key-check": typeof NoUnsafeRsaKeyCheck;
    "@security/no-unsafe-rsa-sign-check": typeof NoUnsafeRsaSignCheck;
    "@cross-device-app-dev/one-multi-breakpoint-check": typeof OneMultiBreakpointCheck;
    "@stability/avoid-inspector-interface-check": typeof AvoidInspectorInterfaceCheck;
    "@stability/await-time-sequence-normal-check": typeof AwaitTimeSequenceNormalCheck;
    "@stability/ban-callback-operations-check": typeof BanCallbackOperationsCheck;
    "@stability/call-addInput-before-addOutput-check": typeof CallAddInputBeforeAddOutputCheck;
    "@stability/camera-input-open-check": typeof CameraInputOpenCheck;
    "@software-sec/checker19241042/command-execution-check": typeof CommandExecutionCheck;
};
export declare const projectRules: {
    '@correctness/audio-interrupt-check': typeof AudioInterruptCheck;
    '@performance/start-window-icon-check': typeof StartWindowIconCheck;
    '@correctness/audio-pause-or-mute-check': typeof AudioPauseOrMuteCheck;
    "@correctness/avsession-buttons-check": typeof AvsessionButtonsCheck;
    "@correctness/avsession-metadata-check": typeof AvsessionMetadataCheck;
    "@security/specified-interface-call-chain-check": typeof SymbolUsageCheck;
    "@performance/number-init-check": typeof NumberInitCheck;
    "@performance/image-sync-load-check": typeof ImageSyncLoadCheck;
    "@performance/list-in-scroll-check": typeof ListInScrollCheck;
    "@performance/high-frequency-log-check": typeof HighFrequencyLogCheck;
    "@performance/lottie-animation-destroy-check": typeof LottieAnimationDestoryCheck;
    "@performance/multiple-associations-state-var-check": typeof MultipleAssociationsStateVarCheck;
    "@performance/set-cached-count-for-lazyforeach-check": typeof SetCachedCountForLazyforeachCheck;
    "@performance/homepage-prepare-load-check": typeof HomepagePrepareLoadCheck;
    "@performance/image-format-check": typeof ImageFormatCheck;
    "@performance/image-size-check": typeof ImageSizeCheck;
    "@performance/page-prefetch-check": typeof PagePrefetchCheck;
    "@performance/resources-file-check": typeof ResourcesFileCheck;
    "@performance/dark-color-mode-check": typeof DarkColorModeCheck;
    "@security/no-cycle-check": typeof NoCycleCheck;
    "@stability/image-sync-blur-check": typeof ImageSyncBlurCheck;
    "@software-sec/checker23373456/command-execution-check": typeof CommandExecutionCheck23373456;
    "@software-sec/checker23373456/hardcoded-secret-check": typeof HardcodedSecretCheck;
    "@software-sec/checker23373456/sql-injection-check": typeof SQLInjectionCheck;
    "@software-sec/checker23373456/path-traversal-check": typeof PathTraversalCheck;
};
export declare const file2CheckRuleMap: Map<string, any>;
export declare const project2CheckRuleMap: Map<string, any>;
export declare class ProxyChecker {
    static getClass(ruleId: string): any;
}
