/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
import {Bar_asn} from './NamingConvention'
import {Bar_Foo} from './NamingConvention'


export class bar {
  public Meth() {
    console.info('method');
  }
}

export function Foo() {
  console.info('function');
}

let User_name = 0;
const _Pbc = 2
let Username = 0;
const invalid_Cases = [];
let asd_0 = 0;