/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {asn} from './NamingConvention'
import {Foo} from './NamingConvention'


export class Bar {
  public meth() {
    console.info('method');
  }
}

export function foo() {
  console.info('function');
}

let USER_ANB = 0;
let abc = 0;
let ABC = 0;
let userName =0;
let asd0 = 0;